import { POLICY_DEFS } from '../../game/data/officerAttributes';
import { CatalogModal, type CatalogItem, type CatalogCategory } from './CatalogModal';
import { useLanguage } from '../i18n';

const POLICY_CATEGORY: Record<string, string> = {
  // ── economy ──
  tuntian:             'economy',
  hydraulics:          'economy',
  commerce:            'economy',
  'salt-monopoly':     'economy',
  'iron-monopoly':     'economy',
  coinage:             'economy',
  'silk-trade':        'economy',
  'tea-trade':         'economy',
  'land-reform':       'economy',
  'poor-relief':       'economy',
  // ── civil ──
  scholarship:         'civil',
  legalism:            'civil',
  rites:               'civil',
  medicine:            'civil',
  'nine-grade':        'civil',
  inspection:          'civil',
  'ancestor-rites':    'civil',
  astronomy:           'civil',
  'calendar-reform':   'civil',
  // ── military ──
  engineering:         'military',
  recruitment:         'military',
  smithing:            'military',
  'horse-stewardship': 'military',
  'military-theory':   'military',
  'naval-academy':     'military',
  'crossbow-corps':    'military',
  'border-garrison':   'military',
  'siege-school':      'military',
  // ── diplomacy / intel ──
  'alliance-marriage': 'diplomacy',
  'tribute-system':    'diplomacy',
  'spy-network':       'diplomacy',
  propaganda:          'diplomacy',
  'frontier-pacification': 'diplomacy',
  // ── new economy ──
  granary:             'economy',
  'maritime-trade':    'economy',
  'silk-loom':         'economy',
  'ox-plowing':        'economy',
  'fish-salt':         'economy',
  // ── new military ──
  fortifications:      'military',
  'ambush-corps':      'military',
  'mountain-warfare':  'military',
  conscription:        'military',
  'elite-guards':      'military',
  arsenal:             'military',
  // ── new civil ──
  'imperial-academy':  'civil',
  'post-roads':        'civil',
  'community-granary': 'civil',
  'court-music':       'civil',
  buddhism:            'civil',
  taoism:              'civil',
  divination:          'civil',
  // ── new diplomacy / intel ──
  'hostage-system':    'diplomacy',
  assassins:           'diplomacy',
  'counter-intel':     'diplomacy',
  'defector-reward':   'diplomacy',
  // ── Phase 3 economy ──
  'iron-tools':        'economy',
  'caravan-protection':'economy',
  'horse-trade':       'economy',
  'copper-mining':     'economy',
  'iron-mining':       'economy',
  timber:              'economy',
  'pearl-trade':       'economy',
  'jade-trade':        'economy',
  corvee:              'economy',
  'tax-light':         'economy',
  // ── Phase 3 military ──
  'watch-towers':      'military',
  'garrison-rotation': 'military',
  'chariot-corps':     'military',
  'shield-wall':       'military',
  'naval-fireships':   'military',
  'naval-rams':        'military',
  'horse-armor':       'military',
  'mountain-stronghold': 'military',
  // ── Phase 3 civil ──
  'household-register':'civil',
  examination:         'civil',
  'mourning-rites':    'civil',
  library:             'civil',
  'music-bureau':      'civil',
  'school-village':    'civil',
  'imperial-edict':    'civil',
  // ── Phase 3 religion (under civil chip) ──
  'five-emperors':     'civil',
  'mountain-spirit':   'civil',
  'river-god':         'civil',
  // ── Phase 3 diplomacy ──
  'envoy-bureau':      'diplomacy',
  'frontier-market':   'diplomacy',
  'captives-ransom':   'diplomacy',
  // ── Phase 4 economy ──
  'gold-mining':       'economy',
  'forest-conservation': 'economy',
  pottery:             'economy',
  lacquerware:         'economy',
  'merchant-guild':    'economy',
  'river-customs':     'economy',
  'pawn-bureau':       'economy',
  'court-treasury':    'economy',
  'bamboo-craft':      'economy',
  'sericulture-tax':   'economy',
  // ── Phase 4 military ──
  'archery-school':    'military',
  'military-drill':    'military',
  'supply-train':      'military',
  'siege-tower':       'military',
  'engineer-corps':    'military',
  'frontier-cavalry':  'military',
  'mountain-passes':   'military',
  watchnight:          'military',
  'spear-corps':       'military',
  'assault-troops':    'military',
  // ── Phase 4 civil ──
  'noble-titles':      'civil',
  'imperial-tour':     'civil',
  'charity-house':     'civil',
  mediation:           'civil',
  'standardize-weights': 'civil',
  'standardize-script':  'civil',
  'map-survey':        'civil',
  'crime-amnesty':     'civil',
  'temple-building':   'civil',
  'new-year-rites':    'civil',
  alchemy:             'civil',
  'soul-prayer':       'civil',
  // ── Phase 4 diplomacy ──
  bribery:             'diplomacy',
  'propaganda-songs':  'diplomacy',
  'nanman-tribute':    'diplomacy',
  // ── Phase 5 economy ──
  ironworks:           'economy',
  shipyard:            'economy',
  canal:               'economy',
  'water-mill':        'economy',
  weaving:             'economy',
  'silver-mining':     'economy',
  'tea-cultivation':   'economy',
  bridges:             'economy',
  caravansary:         'economy',
  'river-dredging':    'economy',
  'horse-breeding':    'economy',
  'famine-loans':      'economy',
  // ── Phase 5 military ──
  'skirmish-corps':    'military',
  'light-cavalry':     'military',
  'bandit-suppression': 'military',
  'pirate-suppression': 'military',
  'veteran-pension':   'military',
  'military-academy':  'military',
  'moat-construction': 'military',
  'camp-discipline':   'military',
  'river-watchtower':  'military',
  'coastal-fortress':  'military',
  // ── Phase 5 civil ──
  'six-ministers':     'civil',
  protocol:            'civil',
  'royal-physicians':  'civil',
  'imperial-guard':    'civil',
  'official-promotion': 'civil',
  'royal-park':        'civil',
  'prefecture-reform': 'civil',
  'land-survey':       'civil',
  // ── religion (civil chip) ──
  'sky-altar':         'civil',
  'earth-altar':       'civil',
  'mountain-pilgrimage': 'civil',
  'ancestral-temple':  'civil',
  // ── Phase 5 frontier diplomacy ──
  'xianbei-buffer':    'diplomacy',
  'xiongnu-tribute':   'diplomacy',
  'qiang-pacification': 'diplomacy',
  'wuhuan-buffer':     'diplomacy',
  'jiao-pacification': 'diplomacy',
  'liaodong-buffer':   'diplomacy',
};

export const POLICY_DESC: Record<string, string> = {
  // ── economy ──
  tuntian:             '屯田 — 兵農合一，駐軍墾荒。糧食產量 +25%，募兵 +10%。',
  hydraulics:          '治水 — 修堤築壩，灌溉農田。農業上限 +15，水攻防 +20%。',
  commerce:            '商業 — 興市通商，鼓勵交易。商業上限 +15，金收入 +20%。',
  'salt-monopoly':     '鹽政 — 國家專營食鹽。每季金 +60，民忠 −1 (官鹽價貴)。',
  'iron-monopoly':     '鐵政 — 國家專營鐵器。武器產量 +30%，城防 +10%。',
  coinage:             '鑄幣 — 整頓貨幣，鑄造五銖。商業收入 +15%，通膨控制。',
  'silk-trade':        '絲綢之路 — 西域商道暢通。金收入 +25%，與西涼諸夷外交 +1。',
  'tea-trade':         '茶馬貿易 — 與羌人換馬。馬政效率 +15%，邊境穩定 +1。',
  'land-reform':       '均田 — 重新分配田地。民忠 +5，農業 +10%，世族敵意 +1。',
  'poor-relief':       '賑災 — 設立常平倉，凶年放糧。瘟疫機率 −30%，民忠每季 +1。',
  // ── civil ──
  scholarship:         '學問 — 興建學館，培育人才。武將招募成功率 +20%，新生 INT +5。',
  legalism:            '法治 — 嚴明法令，重典治世。城市忠誠 +10，叛亂概率減半。',
  rites:               '禮樂 — 制禮作樂，安撫民心。民忠每季 +1，文官效率 +15%。',
  medicine:            '醫術 — 軍醫進駐，療傷救命。瘟疫概率 −50%，負傷恢復 −1 季。',
  'nine-grade':        '九品中正 — 陳群所創。優秀世族子弟自動晉陞 (HIGH INT)，但寒門上升困難。',
  inspection:          '監察 — 設御史台稽查吏治。腐敗 −50%，金庫不漏。',
  'ancestor-rites':    '宗廟祭祀 — 帝王正統的禮制。皇族忠誠 +10，建國儀典加分。',
  astronomy:           '天文 — 觀象授時。徵兆預測 +1，奇門遁甲類戰法增強。',
  'calendar-reform':   '曆法 — 頒布新曆。農時準確 +5%，朝廷威信 +5。',
  // ── military ──
  engineering:         '工兵 — 攻城器械研發。攻城傷害 +25%，城防 +10%。',
  recruitment:         '養兵 — 練兵備戰，訓練精銳。兵力上限 +20%，士兵素質 +1。',
  smithing:            '鍛造 — 鑄造兵刃。武器物品銳氣 +5，武將攻擊 +5。',
  'horse-stewardship': '馬政 — 養馬育駒，騎兵改革。騎兵戰力 +20%，新馬獲取率 +10%。',
  'military-theory':   '軍學 — 設兵書院，研讀兵法。陣形效果 +15%，計策成功率 +10%。',
  'naval-academy':     '水軍 — 訓練水兵戰船。水戰能力 +30%，沿江沿海守備強化。',
  'crossbow-corps':    '弩兵 — 諸葛連弩量產。弓兵射程 +1，齊射傷害 +20%。',
  'border-garrison':   '邊防 — 邊境永久駐軍。邊城防禦 +25%，異族入侵 −30%。',
  'siege-school':      '攻城 — 工程兵專業化。攻城速度 +30%，城牆減耗 −20%。',
  // ── diplomacy / intel ──
  'alliance-marriage': '和親 — 與鄰國通婚。與目標勢力外交關係 +30，盟約穩定。',
  'tribute-system':    '朝貢 — 確立宗主地位。附屬勢力每季貢金 +50。',
  'spy-network':       '細作 — 培訓間諜。敵情可視範圍 +1 城，計謀成功率 +15%。',
  propaganda:          '檄文 — 起草檄文討伐。戰前敵兵叛逃率 +5%，盟友參戰意願 +15。',
  'frontier-pacification': '撫夷 — 攻心為上，南撫蠻夷。南方/西涼異族叛亂 −60%，可徵召蠻兵。',
  // ── new economy ──
  granary:             '倉廩 — 設常平倉。糧價穩定，凶年無饑民，金庫每季 −20 維護。',
  'maritime-trade':    '海貿 — 沿海港口開放。每季金 +80，需港口城。東吳特色。',
  'silk-loom':         '蠶桑 — 推廣蠶絲。商業 +10，可生產絲綢進貢/外銷。',
  'ox-plowing':        '牛耕 — 鼓勵牛拉重犁。農業上限 +12，農時 −15%。',
  'fish-salt':         '漁鹽 — 沿海漁鹽兼營。糧 +15%，金 +40/季，需沿海城。',
  // ── new military ──
  fortifications:      '城防 — 加固城牆建箭樓。城防 +30%，攻城時間 +30%。',
  'ambush-corps':      '伏兵營 — 林山伏擊訓練。伏兵戰法成功率 +25%，森林/山地戰力 +15%。',
  'mountain-warfare':  '山戰 — 山地行軍與作戰。山地移動 ×2，山地傷害 +20%。',
  conscription:        '徵兵 — 大規模強徵。兵力上限 +35%，但民忠 −1/季、農業 −10%。',
  'elite-guards':      '親衛 — 培訓親衛精銳。主將護衛 +40 兵，主將戰死率 −50%。',
  arsenal:             '軍械庫 — 設中央軍械庫。出征自動配發兵器，每月 −15g 維護。',
  // ── new civil ──
  'imperial-academy':  '太學 — 設立太學。學者武將每季 INT +1，可培養儒生官吏。',
  'post-roads':        '驛站 — 全國驛站。命令傳達 +1 城/季，行軍速度 +10%。',
  'community-granary': '義倉 — 鄉社互助糧倉。災情自動賑濟，民忠 +3，金庫 −30/季。',
  'court-music':       '雅樂 — 朝廷正樂。文官效率 +10%，外賓禮節分 +5。',
  // ── cultural / religious ──
  buddhism:            '佛教 — 建寺度僧。民忠 +3/季，少部分人口出家不耕戰 (−5%)。',
  taoism:              '道教 — 設道觀。瘟疫 −30%，秘術系戰法 +10% 成功率。',
  divination:          '卜筮 — 太卜署。重大決策前可窺天意，戰前資訊 +1 條。',
  // ── new diplomacy / intel ──
  'hostage-system':    '質子 — 收他國貴族為質。盟約穩定 ×2，對方背叛代價 ×3。',
  assassins:           '刺客 — 培養死士。可派遣刺殺敵將，成功率隨 INT 提升。',
  'counter-intel':     '反間 — 反查細作。敵方間諜成功率 −50%，可植入假情報。',
  'defector-reward':   '招降 — 厚賞降將。敵將戰敗投降概率 +20%。',
  // ── Phase 3 economy ──
  'iron-tools':        '鐵具 — 鐵農具普及。農業 +20%，需 iron-mining 政策。',
  'caravan-protection':'護商 — 沿途設亭驛。商隊損失 −50%，商業 +10%。',
  'horse-trade':       '馬市 — 邊境馬市。每季新馬 +30 匹，與羌/匈奴互市。',
  'copper-mining':     '銅礦 — 開銅礦。金 +50/季，需有銅礦資源城。',
  'iron-mining':       '鐵礦 — 開鐵礦。鍛造效率 +50%，需鐵礦資源城。',
  timber:              '林業 — 林場伐木。造船/攻城器械成本 −30%。',
  'pearl-trade':       '珍珠貿 — 沿海珍珠採集。金 +60/季，需沿海城。東吳特色。',
  'jade-trade':        '玉貿 — 西域玉器貿易。金 +40，外交禮品 +1 等級。',
  corvee:              '力役 — 徵召民夫服勞役。工程速度 ×1.5，民忠 −2/季。',
  'tax-light':         '輕徭薄賦 — 減免稅賦。民忠 +5，但金收入 −20%。',
  // ── Phase 3 military ──
  'watch-towers':      '烽燧 — 邊境烽火預警。敵軍入侵預警 +1 季。',
  'garrison-rotation': '番上 — 駐軍輪換。守軍士氣 −30% 損耗，疲勞 −50%。',
  'chariot-corps':     '戰車 — 戰車軍編成。平原戰力 +20%，山地 −30%。',
  'shield-wall':       '盾陣 — 盾兵密集。受箭傷害 −30%，受魔法/火傷害 −10%。',
  'naval-fireships':   '火船 — 火攻船。水戰中可發動連環船+火攻組合，傷害 ×2。',
  'naval-rams':        '衝角 — 撞角戰術。水戰首擊傷害 +40%，可衝沉敵船。',
  'horse-armor':       '馬鎧 — 鐵騎兵。騎兵防禦 +30%，但移動 −1。',
  'mountain-stronghold': '山寨 — 山地築寨。山地城市防 +25%，可徵召山民兵。',
  // ── Phase 3 civil ──
  'household-register':'戶籍 — 編製戶口冊。稅收 +10%，徵兵效率 +20%。',
  examination:         '察舉 — 漢代察舉制。每季全國發現 1-2 名隱士。',
  'mourning-rites':    '喪禮 — 制定喪禮規格。世族忠誠 +5，但金庫 −20/季。',
  library:             '圖書 — 設置藏書閣。學者武將智力恢復 +1/季。',
  'music-bureau':      '樂府 — 採集民間樂歌。文官+魅力恢復 +1/季。',
  'school-village':    '鄉學 — 廣設鄉校。寒門武將招募 +20%，文化人口 +5%。',
  'imperial-edict':    '詔書 — 帝制下詔。聯軍可發動共同行動，士氣 +5。',
  // ── religion (civil chip) ──
  'five-emperors':     '五帝祭 — 五帝祭祀。皇族正統 +10，建國加分。',
  'mountain-spirit':   '山神祭 — 祭祀山神。山地城市忠誠 +5，山民歸附 +1。',
  'river-god':         '河神祭 — 祭祀河神。水患減半，水軍出兵時士氣 +3。',
  // ── Phase 3 diplomacy ──
  'envoy-bureau':      '鴻臚寺 — 設外交使團。可同時派 3 個使節，外交效率 +30%。',
  'frontier-market':   '邊市 — 邊境互市。異族貿易金 +50/季，但細作風險 +1。',
  'captives-ransom':   '贖俘 — 贖回戰俘。減少士氣損失，可換回被擒武將。',
  // ── Phase 4 economy ──
  'gold-mining':       '金礦 — 開金礦。每季金 +120，需金礦資源城（稀少）。',
  'forest-conservation':'護林 — 設山林禁伐區。timber 政策效率 +30%，水土流失 −1。',
  pottery:             '陶器 — 陶器作坊。商業 +5/季，民間日用品供應充足。',
  lacquerware:         '漆器 — 漆器精造。高級奢侈品出口，外交禮品 +1 等。',
  'merchant-guild':    '行會 — 建立商會。商業 +12，但商人世族影響 +1。',
  'river-customs':     '関稅 — 江河關卡。每季金 +50，水運效率 −5%。',
  'pawn-bureau':       '質庫 — 官辦當鋪。災年金 +30 (典當收入)，民忠 −1。',
  'court-treasury':    '內庫 — 帝王私帑。奢華消費可獨立，外交賞賜不耗國庫。',
  'bamboo-craft':      '竹器 — 竹器作坊。輕工業 +5%，需有竹林資源。',
  'sericulture-tax':   '桑稅 — 桑田專稅。每季金 +35，但 silk-loom 效率 −10%。',
  // ── Phase 4 military ──
  'archery-school':    '射禮 — 設射禮練弓。弓兵命中 +15%，新兵 WAR 略增。',
  'military-drill':    '演武 — 大演武。全軍士氣 +5%，戰前狀態 +1 季。',
  'supply-train':      '輜重 — 後勤輜重隊。遠征不易斷糧，糧耗 −20%。',
  'siege-tower':       '樓車 — 攻城樓車。攻城傷害 +30%，城牆耐久 −15%。',
  'engineer-corps':    '工程營 — 工程兵編制。築橋/修路/挖壕 ×2 速度。',
  'frontier-cavalry':  '邊騎 — 邊地騎兵。輕騎兵 +20% 機動，可巡邊。',
  'mountain-passes':   '關隘 — 險要設關。山地關卡防禦 +35%，需山地城。',
  watchnight:          '夜禁 — 城內宵禁。內亂概率 −30%，民忠 −1/季。',
  'spear-corps':       '槍隊 — 長槍兵團。剋制騎兵 +25%，平原戰力穩定。',
  'assault-troops':    '突擊隊 — 死士突擊隊。第一回合衝鋒傷害 +40%，但傷亡高。',
  // ── Phase 4 civil ──
  'noble-titles':      '封爵 — 賞賜爵位。武將忠誠 +10，但長期世族化加深。',
  'imperial-tour':     '巡幸 — 帝王巡幸。沿途城市民忠 +5，但奢費 ×2。',
  'charity-house':     '養濟院 — 設孤殘院。民忠 +3，瘟疫 −20%，金 −25/季。',
  mediation:           '鄉約 — 鄉里調解。內亂概率 −15%，民忠 +2。',
  'standardize-weights':'度量衡 — 統一度量。商業 +10%，稅收 +5%，內政效率 +5。',
  'standardize-script':'文字 — 統一文字。文化人口 +5%，行政效率 +10%。',
  'map-survey':        '圖經 — 全國繪圖。軍事偵察 +1 級，行軍路線優化。',
  'crime-amnesty':     '大赦 — 大赦天下。民忠 +8 (一次性)，但盜賊 +10%。',
  // ── religion (civil chip) ──
  'temple-building':   '寺廟 — 大規模建寺。民忠 +3，但金 −40/季，部分人口出家。',
  'new-year-rites':    '元正 — 元正大朝。每年初士氣 +10%，外賓必至。',
  alchemy:             '煉丹 — 道家煉丹。可採尋長生丹藥，武將壽命延長機率。',
  'soul-prayer':       '招魂 — 為陣亡士兵招魂。戰後士氣恢復 +10%。',
  // ── Phase 4 diplomacy ──
  bribery:             '收買 — 賄賂敵方官吏。敵情獲取 +30%，敵國民忠 −5%。',
  'propaganda-songs':  '童謠 — 政治童謠散布。敵國民忠每季 −1，難以追蹤源頭。',
  'nanman-tribute':    '南蠻朝貢 — 收南蠻朝貢。每季金 +40 + 象 +1，需 frontier-pacification。',
  // ── Phase 5 economy ──
  ironworks:           '鐵冶 — 國營鐵冶。武器產量 +25%，需 iron-mining 配套。',
  shipyard:            '造船廠 — 大型造船廠。每季新船 +5，水軍規模 +20%。',
  canal:               '運河 — 開鑿運河。糧運效率 ×2，金 −80 一次性建設費。',
  'water-mill':        '水車 — 水力磨坊。糧產 +12%，需河流城市。',
  weaving:             '紡織 — 國營紡織坊。商業 +8，士兵冬裝普及。',
  'silver-mining':     '銀礦 — 開銀礦。金 +90/季，需銀礦資源城（稀少）。',
  'tea-cultivation':   '茶園 — 茶樹種植。茶葉商業 +10，可外貿。',
  bridges:             '修橋 — 大規模建橋。行軍速度 +10%，水運便利。',
  caravansary:         '驛館 — 沿途館驛。商旅疲勞 −50%，商業 +5%。',
  'river-dredging':    '浚河 — 定期疏浚河道。洪災 −50%，水運效率 +15%。',
  'horse-breeding':    '牧苑 — 國家牧場。每季新馬 +50 匹，騎兵補充加速。',
  'famine-loans':      '借糧 — 凶年借糧。災年民忠不下滑，金 −60 借出。',
  // ── Phase 5 military ──
  'skirmish-corps':    '散兵 — 散兵騷擾。森林伏擊 +20%，但正面戰力低。',
  'light-cavalry':     '輕騎 — 輕騎偵察。情報範圍 +1 城，騎兵機動 +1。',
  'bandit-suppression': '剿匪 — 剿匪安境。山賊 −80%，治安 +20%，民忠 +3。',
  'pirate-suppression': '剿海寇 — 剿沿海寇。沿海安全 +25%，商業 +10%。',
  'veteran-pension':   '退伍 — 老兵養贍。武將自然死亡 −10%，士兵忠誠 +5%。',
  'military-academy':  '武備學堂 — 武官學堂。每季新生武將 WAR/LED +5。',
  'moat-construction': '護城河 — 環城護城河。城防 +20%，攻城方傷亡 +25%。',
  'camp-discipline':   '軍紀 — 嚴明軍紀。士兵不擾民，民忠 +3，將士忠誠 +10。',
  'river-watchtower':  '江樓 — 江邊瞭望樓。江岸敵情早警 +1 季。',
  'coastal-fortress':  '海防 — 沿海要塞。海上入侵防禦 +30%，海寇 −50%。',
  // ── Phase 5 civil ──
  'six-ministers':     '三公九卿 — 中央官制改革。行政效率 +25%，世族影響 +1。',
  protocol:            '朝儀 — 朝堂禮儀。外交禮節 +1 等，朝臣不亂禮。',
  'royal-physicians':  '太醫 — 設太醫署。皇帝/重臣壽命延長機率，瘟疫 −20%。',
  'imperial-guard':    '禁衛 — 皇宮禁衛。京城叛亂幾乎不可能，金 −30/季。',
  'official-promotion': '升遷 — 正規升遷制度。武將升職速度 +20%。',
  'royal-park':        '苑囿 — 皇家園林。皇族享樂，民忠 −3，奢費 +50/季。',
  'prefecture-reform': '郡縣改革 — 重劃郡縣。內政效率 +15%，地方影響 −1。',
  'land-survey':       '計畝 — 全國丈量田畝。稅收 +15%，民忠 −2（豪族抵制）。',
  // ── religion (civil chip) ──
  'sky-altar':         '圜丘 — 圜丘祭天。帝制正統 +15，建國儀禮 +1 等。',
  'earth-altar':       '方丘 — 方丘祭地。豐收禱告，農業 +5%。',
  'mountain-pilgrimage': '朝山 — 五嶽朝山。聖山城市忠誠 +5，可培養道士。',
  'ancestral-temple':  '太廟 — 太廟祭祀。皇族忠誠 +15，子孫合法繼承。',
  // ── Phase 5 frontier diplomacy ──
  'xianbei-buffer':    '鮮卑緩衝 — 邊境設緩衝區。鮮卑入侵 −60%，邊境 horse-trade +。',
  'xiongnu-tribute':   '匈奴朝貢 — 匈奴稱臣納貢。每季金 +30 + 馬 +20。',
  'qiang-pacification': '羌族安撫 — 撫西涼羌族。叛亂 −70%，可徵羌騎。',
  'wuhuan-buffer':     '烏桓緩衝 — 治理烏桓。東北邊境 +50% 穩定。',
  'jiao-pacification': '交州安撫 — 安南越族。南方城市 +5 民忠，可開南海貿易。',
  'liaodong-buffer':   '遼東緩衝 — 公孫氏邊境。遼東叛亂 −80%。',
};

// English descriptions — shown in English mode (falls back to zh if missing).
export const POLICY_DESC_EN: Record<string, string> = {
  // economy
  tuntian:             'Tuntian — soldier-farmers work the land. Food output +25%, recruitment +10%.',
  hydraulics:          'Hydraulics — dykes and irrigation. Agriculture cap +15, water-attack defense +20%.',
  commerce:            'Commerce — open markets, spur trade. Commerce cap +15, gold income +20%.',
  'salt-monopoly':     'Salt Monopoly — state salt trade. +60 gold/season, loyalty −1 (dear salt).',
  'iron-monopoly':     'Iron Monopoly — state ironworks. Weapon output +30%, city defense +10%.',
  coinage:             'Coinage — mint standard cash. Commerce income +15%, inflation curbed.',
  'silk-trade':        'Silk Road — open the western trade routes. Gold income +25%, +1 diplomacy with Liang/western tribes.',
  'tea-trade':         'Tea-Horse Trade — trade with the Qiang for horses. Horse husbandry +15%, border stability +1.',
  'land-reform':       'Land Reform — redistribute fields. Loyalty +5, agriculture +10%, +1 gentry hostility.',
  'poor-relief':       'Poor Relief — ever-normal granaries, famine grain. Plague chance −30%, loyalty +1/season.',
  // civil
  scholarship:         'Scholarship — found academies, nurture talent. Recruit success +20%, new officers INT +5.',
  legalism:            'Legalism — strict law, firm rule. City loyalty +10, revolt chance halved.',
  rites:               'Rites & Music — ritual to settle the people. Loyalty +1/season, civil-officer efficiency +15%.',
  medicine:            'Medicine — field physicians. Plague chance −50%, wound recovery −1 season.',
  'nine-grade':        'Nine-Rank System — Chen Qun’s reform. Able gentry scions auto-promote (high INT); commoners rise hard.',
  inspection:          'Inspection — censorate oversees officials. Corruption −50%, treasury never leaks.',
  'ancestor-rites':    'Ancestral Rites — rites of imperial legitimacy. Royal-clan loyalty +10, bonus to founding ceremonies.',
  astronomy:           'Astronomy — read the heavens. Omen prediction +1, mystic-art tactics strengthened.',
  'calendar-reform':   'Calendar Reform — promulgate a new calendar. Farming timing +5%, court prestige +5.',
  // military
  engineering:         'Engineering — siege-engine research. Siege damage +25%, city defense +10%.',
  recruitment:         'Drilling — train elite troops. Troop cap +20%, soldier quality +1.',
  smithing:            'Smithing — forge fine arms. Weapon items +5 edge, officer attack +5.',
  'horse-stewardship': 'Horse Stewardship — breed mounts, reform cavalry. Cavalry power +20%, new-horse rate +10%.',
  'military-theory':   'Military Theory — study the art of war. Formation effect +15%, stratagem success +10%.',
  'naval-academy':     'Naval Academy — train marines and warships. Naval combat +30%, river/coast defense bolstered.',
  'crossbow-corps':    'Crossbow Corps — mass repeating crossbows. Archer range +1, volley damage +20%.',
  'border-garrison':   'Border Garrison — permanent frontier troops. Border-city defense +25%, incursions −30%.',
  'siege-school':      'Siege School — professional engineers. Siege speed +30%, wall wear −20%.',
  // diplomacy / intel
  'alliance-marriage': 'Marriage Alliance — wed a neighbor’s house. +30 relations with the target force, stable pacts.',
  'tribute-system':    'Tribute System — assert suzerainty. Vassal forces pay +50 gold/season.',
  'spy-network':       'Spy Network — train agents. Enemy intel range +1 city, stratagem success +15%.',
  propaganda:          'Manifesto — draft a call to arms. Pre-battle enemy desertion +5%, allies +15% willing to join.',
  'frontier-pacification': 'Pacify the Frontier — win hearts in the south. Southern/Liang tribal revolts −60%, can levy tribal troops.',
  // new economy
  granary:             'Granary — ever-normal stores. Stable grain prices, no famine victims, −20 gold/season upkeep.',
  'maritime-trade':    'Maritime Trade — open coastal ports. +80 gold/season, needs a port city. A Wu specialty.',
  'silk-loom':         'Sericulture — promote silk. Commerce +10, can produce silk for tribute/export.',
  'ox-plowing':        'Ox Plowing — heavy ox-drawn ploughs. Agriculture cap +12, farming time −15%.',
  'fish-salt':         'Fishing & Salt — coastal fisheries and salt. Food +15%, +40 gold/season, needs a coastal city.',
  // new military
  fortifications:      'Fortifications — reinforced walls and towers. City defense +30%, siege time +30%.',
  'ambush-corps':      'Ambush Corps — trained for forest/mountain ambush. Ambush-tactic success +25%, forest/mountain power +15%.',
  'mountain-warfare':  'Mountain Warfare — highland marching and combat. Mountain movement ×2, mountain damage +20%.',
  conscription:        'Conscription — mass forced levy. Troop cap +35%, but loyalty −1/season and agriculture −10%.',
  'elite-guards':      'Elite Guards — train a bodyguard corps. Commander escort +40 troops, commander death rate −50%.',
  arsenal:             'Arsenal — central armory. Auto-issues weapons on campaign, −15g/month upkeep.',
  // new civil
  'imperial-academy':  'Imperial Academy — found the Taixue. Scholar officers +1 INT/season, trains Confucian officials.',
  'post-roads':        'Post Roads — national relay stations. Order reach +1 city/season, march speed +10%.',
  'community-granary': 'Community Granary — village mutual-aid stores. Auto-relief in disasters, loyalty +3, −30 gold/season.',
  'court-music':       'Court Music — proper court music. Civil-officer efficiency +10%, +5 envoy courtesy.',
  // cultural / religious
  buddhism:            'Buddhism — build temples, ordain monks. Loyalty +3/season; a few leave farm/war (−5%).',
  taoism:              'Taoism — found Daoist abbeys. Plague −30%, mystic-art tactics +10% success.',
  divination:          'Divination — Office of the Grand Diviner. Glimpse fate before big decisions, +1 pre-battle intel.',
  // new diplomacy / intel
  'hostage-system':    'Hostage System — hold foreign nobles. Pact stability ×2, betrayal cost ×3.',
  assassins:           'Assassins — train deathsmen. Send assassins against enemy officers; success scales with INT.',
  'counter-intel':     'Counter-Intelligence — hunt enemy spies. Enemy spy success −50%, can plant false intel.',
  'defector-reward':   'Clemency — reward defectors. Defeated enemy officers +20% to surrender.',
  // Phase 3 economy
  'iron-tools':        'Iron Tools — iron farm tools spread. Agriculture +20%, needs the iron-mining policy.',
  'caravan-protection':'Caravan Guard — relay posts along roads. Caravan losses −50%, commerce +10%.',
  'horse-trade':       'Horse Market — frontier horse fairs. +30 horses/season, trade with Qiang/Xiongnu.',
  'copper-mining':     'Copper Mining — work copper. +50 gold/season, needs a copper-resource city.',
  'iron-mining':       'Iron Mining — work iron. Smithing efficiency +50%, needs an iron-resource city.',
  timber:              'Forestry — logging camps. Ship/siege-engine cost −30%.',
  'pearl-trade':       'Pearl Trade — coastal pearl diving. +60 gold/season, needs a coastal city. A Wu specialty.',
  'jade-trade':        'Jade Trade — western jade trade. +40 gold, diplomatic gifts +1 grade.',
  corvee:              'Corvée — levy laborers. Construction speed ×1.5, loyalty −2/season.',
  'tax-light':         'Light Taxes — ease the burden. Loyalty +5, but gold income −20%.',
  // Phase 3 military
  'watch-towers':      'Beacon Towers — frontier fire-signals. Invasion warning +1 season.',
  'garrison-rotation': 'Garrison Rotation — rotate defenders. Defender morale loss −30%, fatigue −50%.',
  'chariot-corps':     'Chariot Corps — war-chariot units. Plains power +20%, mountains −30%.',
  'shield-wall':       'Shield Wall — massed shieldmen. Arrow damage −30%, magic/fire damage −10%.',
  'naval-fireships':   'Fireships — fire-attack ships. Can chain-and-burn enemy ships, damage ×2.',
  'naval-rams':        'Ramming Prows — ram tactics. Naval first-strike +40%, can sink enemy ships.',
  'horse-armor':       'Barding — armored cavalry. Cavalry defense +30%, but movement −1.',
  'mountain-stronghold': 'Mountain Stronghold — highland forts. Mountain-city defense +25%, can levy hill militia.',
  // Phase 3 civil
  'household-register':'Household Register — census rolls. Tax +10%, conscription efficiency +20%.',
  examination:         'Recommendation — Han recommendation system. 1–2 hermits found nationwide each season.',
  'mourning-rites':    'Mourning Rites — formal funeral rites. Gentry loyalty +5, but −20 gold/season.',
  library:             'Library — establish a book repository. Scholar officers’ INT recovery +1/season.',
  'music-bureau':      'Music Bureau — collect folk songs. Civil officers’ CHA recovery +1/season.',
  'school-village':    'Village Schools — schools everywhere. Commoner-officer recruitment +20%, cultured population +5%.',
  'imperial-edict':    'Imperial Edict — decree under empire. Coalitions can take joint action, morale +5.',
  // religion
  'five-emperors':     'Rite of Five Emperors — sacrifice to the Five Emperors. Royal legitimacy +10, founding bonus.',
  'mountain-spirit':   'Mountain-Spirit Rite — worship mountain gods. Mountain-city loyalty +5, +1 hillfolk allegiance.',
  'river-god':         'River-God Rite — worship river gods. Flood damage halved, +3 navy morale on sortie.',
  // Phase 3 diplomacy
  'envoy-bureau':      'Office of Envoys — diplomatic corps. Send 3 envoys at once, diplomacy efficiency +30%.',
  'frontier-market':   'Frontier Market — border trade fairs. +50 gold/season from tribal trade, but spy risk +1.',
  'captives-ransom':   'Ransom — buy back captives. Less morale loss, can recover captured officers.',
  // Phase 4 economy
  'gold-mining':       'Gold Mining — work gold. +120 gold/season, needs a (rare) gold-resource city.',
  'forest-conservation':'Forest Reserve — protected logging zones. Timber-policy efficiency +30%, erosion −1.',
  pottery:             'Pottery — pottery workshops. Commerce +5/season, ample everyday goods.',
  lacquerware:         'Lacquerware — fine lacquer. Luxury export, diplomatic gifts +1 grade.',
  'merchant-guild':    'Merchant Guild — found trade guilds. Commerce +12, but merchant-gentry influence +1.',
  'river-customs':     'River Tolls — river checkpoints. +50 gold/season, river-transport efficiency −5%.',
  'pawn-bureau':       'Pawn Bureau — state pawnshops. Famine-year +30 gold (pawn income), loyalty −1.',
  'court-treasury':    'Privy Purse — the ruler’s private treasury. Luxury self-funds; gifts don’t drain the state.',
  'bamboo-craft':      'Bamboo Craft — bamboo workshops. Light industry +5%, needs a bamboo resource.',
  'sericulture-tax':   'Mulberry Tax — dedicated silk-field tax. +35 gold/season, but silk-loom efficiency −10%.',
  // Phase 4 military
  'archery-school':    'Archery School — train at the archery rite. Archer accuracy +15%, recruits’ WAR slightly up.',
  'military-drill':    'Grand Review — great muster. All-army morale +5%, +1 season of battle-readiness.',
  'supply-train':      'Supply Train — logistics columns. Expeditions seldom run dry, grain upkeep −20%.',
  'siege-tower':       'Siege Tower — siege towers. Siege damage +30%, wall durability −15%.',
  'engineer-corps':    'Engineer Corps — combat engineers. Bridge/road/trench work at ×2 speed.',
  'frontier-cavalry':  'Frontier Cavalry — borderland riders. Light cavalry +20% mobility, can patrol the frontier.',
  'mountain-passes':   'Mountain Passes — fortify the passes. Mountain-pass defense +35%, needs a mountain city.',
  watchnight:          'Curfew — night curfew. Unrest chance −30%, loyalty −1/season.',
  'spear-corps':       'Spear Corps — long-spear regiments. +25% vs cavalry, steady on the plains.',
  'assault-troops':    'Assault Troops — deathsmen shock units. First-round charge +40% damage, but high casualties.',
  // Phase 4 civil
  'noble-titles':      'Noble Titles — grant peerages. Officer loyalty +10, but gentrification deepens over time.',
  'imperial-tour':     'Imperial Tour — the ruler progresses. Loyalty +5 along the route, but luxury cost ×2.',
  'charity-house':     'Charity House — homes for the destitute. Loyalty +3, plague −20%, −25 gold/season.',
  mediation:           'Village Pact — local mediation. Unrest chance −15%, loyalty +2.',
  'standardize-weights':'Standard Measures — unify weights. Commerce +10%, tax +5%, admin efficiency +5.',
  'standardize-script':'Standard Script — unify writing. Cultured population +5%, admin efficiency +10%.',
  'map-survey':        'Cartography — survey the realm. Military scouting +1 level, optimized march routes.',
  'crime-amnesty':     'Amnesty — pardon the realm. Loyalty +8 (one-time), but banditry +10%.',
  // religion
  'temple-building':   'Temple Building — build temples widely. Loyalty +3, but −40 gold/season; some people ordain.',
  'new-year-rites':    'New Year Court — grand New Year audience. +10% morale at year’s start, all envoys attend.',
  alchemy:             'Alchemy — Daoist elixirs. May find longevity elixirs; chance to extend officer lifespan.',
  'soul-prayer':       'Soul Prayer — rites for the war dead. Post-battle morale recovery +10%.',
  // Phase 4 diplomacy
  bribery:             'Bribery — bribe enemy officials. Intel gain +30%, enemy loyalty −5%.',
  'propaganda-songs':  'Children’s Rhymes — spread political ditties. Enemy loyalty −1/season, hard to trace.',
  'nanman-tribute':    'Nanman Tribute — collect southern tribute. +40 gold + 1 elephant/season, needs frontier-pacification.',
  // Phase 5 economy
  ironworks:           'State Ironworks — national iron-smelting. Weapon output +25%, pairs with iron-mining.',
  shipyard:            'Shipyard — large shipyards. +5 new ships/season, navy size +20%.',
  canal:               'Canal — dig a canal. Grain transport ×2, −80 gold one-time build cost.',
  'water-mill':        'Water Mill — water-powered mills. Grain output +12%, needs a river city.',
  weaving:             'Weaving — state textile mills. Commerce +8, winter clothing for the troops.',
  'silver-mining':     'Silver Mining — work silver. +90 gold/season, needs a (rare) silver-resource city.',
  'tea-cultivation':   'Tea Plantation — grow tea. Tea commerce +10, exportable.',
  bridges:             'Bridges — build bridges widely. March speed +10%, easier water transport.',
  caravansary:         'Caravansary — wayside inns. Merchant fatigue −50%, commerce +5%.',
  'river-dredging':    'River Dredging — dredge channels regularly. Flood −50%, water transport +15%.',
  'horse-breeding':    'State Pastures — national horse farms. +50 new horses/season, faster cavalry replenishment.',
  'famine-loans':      'Famine Loans — lend grain in lean years. Loyalty holds in disasters, −60 gold lent out.',
  // Phase 5 military
  'skirmish-corps':    'Skirmishers — harassing skirmishers. Forest ambush +20%, but weak head-on.',
  'light-cavalry':     'Light Cavalry — scouting riders. Intel range +1 city, cavalry mobility +1.',
  'bandit-suppression': 'Bandit Suppression — pacify the hills. Bandits −80%, security +20%, loyalty +3.',
  'pirate-suppression': 'Pirate Suppression — clear coastal raiders. Coastal safety +25%, commerce +10%.',
  'veteran-pension':   'Veteran Pension — care for old soldiers. Officer natural death −10%, soldier loyalty +5%.',
  'military-academy':  'Military Academy — officers’ college. New officers WAR/LED +5 each season.',
  'moat-construction': 'Moat — encircling moat. City defense +20%, besieger casualties +25%.',
  'camp-discipline':   'Camp Discipline — strict discipline. Troops spare civilians, loyalty +3, officer loyalty +10.',
  'river-watchtower':  'River Watchtower — riverside lookouts. Riverbank early warning +1 season.',
  'coastal-fortress':  'Coastal Fortress — seaside strongholds. Sea-invasion defense +30%, pirates −50%.',
  // Phase 5 civil
  'six-ministers':     'Three Excellencies & Nine Ministers — central office reform. Admin efficiency +25%, gentry influence +1.',
  protocol:            'Court Protocol — court etiquette. Diplomatic courtesy +1 grade, no breaches of decorum.',
  'royal-physicians':  'Imperial Physicians — the Imperial Medical Office. May extend emperor/minister lifespans, plague −20%.',
  'imperial-guard':    'Imperial Guard — palace guards. Capital revolt nearly impossible, −30 gold/season.',
  'official-promotion': 'Promotion System — regular promotion. Officer promotion speed +20%.',
  'royal-park':        'Royal Park — imperial gardens. Royal indulgence: loyalty −3, luxury +50/season.',
  'prefecture-reform': 'Commandery Reform — redraw commanderies. Admin efficiency +15%, local influence −1.',
  'land-survey':       'Land Survey — measure all fields. Tax +15%, loyalty −2 (magnate resistance).',
  // religion
  'sky-altar':         'Round Altar — sacrifice to Heaven. Imperial legitimacy +15, founding rites +1 grade.',
  'earth-altar':       'Square Altar — sacrifice to Earth. Harvest prayers, agriculture +5%.',
  'mountain-pilgrimage': 'Pilgrimage — pilgrimage to the Five Peaks. Holy-mountain city loyalty +5, can train Daoists.',
  'ancestral-temple':  'Ancestral Temple — temple rites. Royal-clan loyalty +15, legitimate succession.',
  // Phase 5 frontier diplomacy
  'xianbei-buffer':    'Xianbei Buffer — a frontier buffer zone. Xianbei incursions −60%, +border horse-trade.',
  'xiongnu-tribute':   'Xiongnu Tribute — the Xiongnu submit. +30 gold + 20 horses/season.',
  'qiang-pacification': 'Qiang Pacification — soothe the Liang Qiang. Revolts −70%, can levy Qiang riders.',
  'wuhuan-buffer':     'Wuhuan Buffer — govern the Wuhuan. Northeast frontier +50% stability.',
  'jiao-pacification': 'Jiaozhou Pacification — pacify the southern Yue. Southern cities +5 loyalty, opens South Sea trade.',
  'liaodong-buffer':   'Liaodong Buffer — the Gongsun frontier. Liaodong revolts −80%.',
};

const CATEGORIES: CatalogCategory[] = [
  { key: 'economy',   zh: '民政', en: 'Economy',   color: '#b8c87a' },
  { key: 'civil',     zh: '文教', en: 'Civil',     color: '#88b7e8' },
  { key: 'military',  zh: '兵備', en: 'Military',  color: '#b8442e' },
  { key: 'diplomacy', zh: '外交', en: 'Diplomacy', color: '#e6c473' },
];

interface Props { onClose: () => void; }

export function PoliciesModal({ onClose }: Props) {
  const lang = useLanguage();
  const items: CatalogItem[] = Object.entries(POLICY_DEFS).map(([id, def]) => ({
    id,
    zh: def.zh,
    en: def.en,
    description: (lang === 'en' ? (POLICY_DESC_EN[id] ?? POLICY_DESC[id]) : POLICY_DESC[id]) ?? '',
    category: POLICY_CATEGORY[id] ?? 'civil',
  }));
  return (
    <CatalogModal
      onClose={onClose}
      title={{ zh: '政策', en: 'Policies' }}
      items={items}
      categories={CATEGORIES}
    />
  );
}
