import { POLICY_DEFS } from '../../game/data/officerAttributes';
import { CatalogModal, type CatalogItem, type CatalogCategory } from './CatalogModal';

const POLICY_CATEGORY: Record<string, string> = {
  // ── economy ──
  tuntian:             'economy',
  hydraulics:          'economy',
  commerce:            'economy',
  'salt-monopoly':     'economy',
  'iron-monopoly':     'economy',
  coinage:             'economy',
  'silk-trade':        'economy',
  'tea-trade':         'economy',
  'land-reform':       'economy',
  'poor-relief':       'economy',
  // ── civil ──
  scholarship:         'civil',
  legalism:            'civil',
  rites:               'civil',
  medicine:            'civil',
  'nine-grade':        'civil',
  inspection:          'civil',
  'ancestor-rites':    'civil',
  astronomy:           'civil',
  'calendar-reform':   'civil',
  // ── military ──
  engineering:         'military',
  recruitment:         'military',
  smithing:            'military',
  'horse-stewardship': 'military',
  'military-theory':   'military',
  'naval-academy':     'military',
  'crossbow-corps':    'military',
  'border-garrison':   'military',
  'siege-school':      'military',
  // ── diplomacy / intel ──
  'alliance-marriage': 'diplomacy',
  'tribute-system':    'diplomacy',
  'spy-network':       'diplomacy',
  propaganda:          'diplomacy',
  'frontier-pacification': 'diplomacy',
  // ── new economy ──
  granary:             'economy',
  'maritime-trade':    'economy',
  'silk-loom':         'economy',
  'ox-plowing':        'economy',
  'fish-salt':         'economy',
  // ── new military ──
  fortifications:      'military',
  'ambush-corps':      'military',
  'mountain-warfare':  'military',
  conscription:        'military',
  'elite-guards':      'military',
  arsenal:             'military',
  // ── new civil ──
  'imperial-academy':  'civil',
  'post-roads':        'civil',
  'community-granary': 'civil',
  'court-music':       'civil',
  buddhism:            'civil',
  taoism:              'civil',
  divination:          'civil',
  // ── new diplomacy / intel ──
  'hostage-system':    'diplomacy',
  assassins:           'diplomacy',
  'counter-intel':     'diplomacy',
  'defector-reward':   'diplomacy',
  // ── Phase 3 economy ──
  'iron-tools':        'economy',
  'caravan-protection':'economy',
  'horse-trade':       'economy',
  'copper-mining':     'economy',
  'iron-mining':       'economy',
  timber:              'economy',
  'pearl-trade':       'economy',
  'jade-trade':        'economy',
  corvee:              'economy',
  'tax-light':         'economy',
  // ── Phase 3 military ──
  'watch-towers':      'military',
  'garrison-rotation': 'military',
  'chariot-corps':     'military',
  'shield-wall':       'military',
  'naval-fireships':   'military',
  'naval-rams':        'military',
  'horse-armor':       'military',
  'mountain-stronghold': 'military',
  // ── Phase 3 civil ──
  'household-register':'civil',
  examination:         'civil',
  'mourning-rites':    'civil',
  library:             'civil',
  'music-bureau':      'civil',
  'school-village':    'civil',
  'imperial-edict':    'civil',
  // ── Phase 3 religion (under civil chip) ──
  'five-emperors':     'civil',
  'mountain-spirit':   'civil',
  'river-god':         'civil',
  // ── Phase 3 diplomacy ──
  'envoy-bureau':      'diplomacy',
  'frontier-market':   'diplomacy',
  'captives-ransom':   'diplomacy',
  // ── Phase 4 economy ──
  'gold-mining':       'economy',
  'forest-conservation': 'economy',
  pottery:             'economy',
  lacquerware:         'economy',
  'merchant-guild':    'economy',
  'river-customs':     'economy',
  'pawn-bureau':       'economy',
  'court-treasury':    'economy',
  'bamboo-craft':      'economy',
  'sericulture-tax':   'economy',
  // ── Phase 4 military ──
  'archery-school':    'military',
  'military-drill':    'military',
  'supply-train':      'military',
  'siege-tower':       'military',
  'engineer-corps':    'military',
  'frontier-cavalry':  'military',
  'mountain-passes':   'military',
  watchnight:          'military',
  'spear-corps':       'military',
  'assault-troops':    'military',
  // ── Phase 4 civil ──
  'noble-titles':      'civil',
  'imperial-tour':     'civil',
  'charity-house':     'civil',
  mediation:           'civil',
  'standardize-weights': 'civil',
  'standardize-script':  'civil',
  'map-survey':        'civil',
  'crime-amnesty':     'civil',
  'temple-building':   'civil',
  'new-year-rites':    'civil',
  alchemy:             'civil',
  'soul-prayer':       'civil',
  // ── Phase 4 diplomacy ──
  bribery:             'diplomacy',
  'propaganda-songs':  'diplomacy',
  'nanman-tribute':    'diplomacy',
  // ── Phase 5 economy ──
  ironworks:           'economy',
  shipyard:            'economy',
  canal:               'economy',
  'water-mill':        'economy',
  weaving:             'economy',
  'silver-mining':     'economy',
  'tea-cultivation':   'economy',
  bridges:             'economy',
  caravansary:         'economy',
  'river-dredging':    'economy',
  'horse-breeding':    'economy',
  'famine-loans':      'economy',
  // ── Phase 5 military ──
  'skirmish-corps':    'military',
  'light-cavalry':     'military',
  'bandit-suppression': 'military',
  'pirate-suppression': 'military',
  'veteran-pension':   'military',
  'military-academy':  'military',
  'moat-construction': 'military',
  'camp-discipline':   'military',
  'river-watchtower':  'military',
  'coastal-fortress':  'military',
  // ── Phase 5 civil ──
  'six-ministers':     'civil',
  protocol:            'civil',
  'royal-physicians':  'civil',
  'imperial-guard':    'civil',
  'official-promotion': 'civil',
  'royal-park':        'civil',
  'prefecture-reform': 'civil',
  'land-survey':       'civil',
  // ── religion (civil chip) ──
  'sky-altar':         'civil',
  'earth-altar':       'civil',
  'mountain-pilgrimage': 'civil',
  'ancestral-temple':  'civil',
  // ── Phase 5 frontier diplomacy ──
  'xianbei-buffer':    'diplomacy',
  'xiongnu-tribute':   'diplomacy',
  'qiang-pacification': 'diplomacy',
  'wuhuan-buffer':     'diplomacy',
  'jiao-pacification': 'diplomacy',
  'liaodong-buffer':   'diplomacy',
};

export const POLICY_DESC: Record<string, string> = {
  // ── economy ──
  tuntian:             '屯田 — 兵農合一，駐軍墾荒。糧食產量 +25%，募兵 +10%。',
  hydraulics:          '治水 — 修堤築壩，灌溉農田。農業上限 +15，水攻防 +20%。',
  commerce:            '商業 — 興市通商，鼓勵交易。商業上限 +15，金收入 +20%。',
  'salt-monopoly':     '鹽政 — 國家專營食鹽。每季金 +60，民忠 −1 (官鹽價貴)。',
  'iron-monopoly':     '鐵政 — 國家專營鐵器。武器產量 +30%，城防 +10%。',
  coinage:             '鑄幣 — 整頓貨幣，鑄造五銖。商業收入 +15%，通膨控制。',
  'silk-trade':        '絲綢之路 — 西域商道暢通。金收入 +25%，與西涼諸夷外交 +1。',
  'tea-trade':         '茶馬貿易 — 與羌人換馬。馬政效率 +15%，邊境穩定 +1。',
  'land-reform':       '均田 — 重新分配田地。民忠 +5，農業 +10%，世族敵意 +1。',
  'poor-relief':       '賑災 — 設立常平倉，凶年放糧。瘟疫機率 −30%，民忠每季 +1。',
  // ── civil ──
  scholarship:         '學問 — 興建學館，培育人才。武將招募成功率 +20%，新生 INT +5。',
  legalism:            '法治 — 嚴明法令，重典治世。城市忠誠 +10，叛亂概率減半。',
  rites:               '禮樂 — 制禮作樂，安撫民心。民忠每季 +1，文官效率 +15%。',
  medicine:            '醫術 — 軍醫進駐，療傷救命。瘟疫概率 −50%，負傷恢復 −1 季。',
  'nine-grade':        '九品中正 — 陳群所創。優秀世族子弟自動晉陞 (HIGH INT)，但寒門上升困難。',
  inspection:          '監察 — 設御史台稽查吏治。腐敗 −50%，金庫不漏。',
  'ancestor-rites':    '宗廟祭祀 — 帝王正統的禮制。皇族忠誠 +10，建國儀典加分。',
  astronomy:           '天文 — 觀象授時。徵兆預測 +1，奇門遁甲類戰法增強。',
  'calendar-reform':   '曆法 — 頒布新曆。農時準確 +5%，朝廷威信 +5。',
  // ── military ──
  engineering:         '工兵 — 攻城器械研發。攻城傷害 +25%，城防 +10%。',
  recruitment:         '養兵 — 練兵備戰，訓練精銳。兵力上限 +20%，士兵素質 +1。',
  smithing:            '鍛造 — 鑄造兵刃。武器物品銳氣 +5，武將攻擊 +5。',
  'horse-stewardship': '馬政 — 養馬育駒，騎兵改革。騎兵戰力 +20%，新馬獲取率 +10%。',
  'military-theory':   '軍學 — 設兵書院，研讀兵法。陣形效果 +15%，計策成功率 +10%。',
  'naval-academy':     '水軍 — 訓練水兵戰船。水戰能力 +30%，沿江沿海守備強化。',
  'crossbow-corps':    '弩兵 — 諸葛連弩量產。弓兵射程 +1，齊射傷害 +20%。',
  'border-garrison':   '邊防 — 邊境永久駐軍。邊城防禦 +25%，異族入侵 −30%。',
  'siege-school':      '攻城 — 工程兵專業化。攻城速度 +30%，城牆減耗 −20%。',
  // ── diplomacy / intel ──
  'alliance-marriage': '和親 — 與鄰國通婚。與目標勢力外交關係 +30，盟約穩定。',
  'tribute-system':    '朝貢 — 確立宗主地位。附屬勢力每季貢金 +50。',
  'spy-network':       '細作 — 培訓間諜。敵情可視範圍 +1 城，計謀成功率 +15%。',
  propaganda:          '檄文 — 起草檄文討伐。戰前敵兵叛逃率 +5%，盟友參戰意願 +15。',
  'frontier-pacification': '撫夷 — 攻心為上，南撫蠻夷。南方/西涼異族叛亂 −60%，可徵召蠻兵。',
  // ── new economy ──
  granary:             '倉廩 — 設常平倉。糧價穩定，凶年無饑民，金庫每季 −20 維護。',
  'maritime-trade':    '海貿 — 沿海港口開放。每季金 +80，需港口城。東吳特色。',
  'silk-loom':         '蠶桑 — 推廣蠶絲。商業 +10，可生產絲綢進貢/外銷。',
  'ox-plowing':        '牛耕 — 鼓勵牛拉重犁。農業上限 +12，農時 −15%。',
  'fish-salt':         '漁鹽 — 沿海漁鹽兼營。糧 +15%，金 +40/季，需沿海城。',
  // ── new military ──
  fortifications:      '城防 — 加固城牆建箭樓。城防 +30%，攻城時間 +30%。',
  'ambush-corps':      '伏兵營 — 林山伏擊訓練。伏兵戰法成功率 +25%，森林/山地戰力 +15%。',
  'mountain-warfare':  '山戰 — 山地行軍與作戰。山地移動 ×2，山地傷害 +20%。',
  conscription:        '徵兵 — 大規模強徵。兵力上限 +35%，但民忠 −1/季、農業 −10%。',
  'elite-guards':      '親衛 — 培訓親衛精銳。主將護衛 +40 兵，主將戰死率 −50%。',
  arsenal:             '軍械庫 — 設中央軍械庫。出征自動配發兵器，每月 −15g 維護。',
  // ── new civil ──
  'imperial-academy':  '太學 — 設立太學。學者武將每季 INT +1，可培養儒生官吏。',
  'post-roads':        '驛站 — 全國驛站。命令傳達 +1 城/季，行軍速度 +10%。',
  'community-granary': '義倉 — 鄉社互助糧倉。災情自動賑濟，民忠 +3，金庫 −30/季。',
  'court-music':       '雅樂 — 朝廷正樂。文官效率 +10%，外賓禮節分 +5。',
  // ── cultural / religious ──
  buddhism:            '佛教 — 建寺度僧。民忠 +3/季，少部分人口出家不耕戰 (−5%)。',
  taoism:              '道教 — 設道觀。瘟疫 −30%，秘術系戰法 +10% 成功率。',
  divination:          '卜筮 — 太卜署。重大決策前可窺天意，戰前資訊 +1 條。',
  // ── new diplomacy / intel ──
  'hostage-system':    '質子 — 收他國貴族為質。盟約穩定 ×2，對方背叛代價 ×3。',
  assassins:           '刺客 — 培養死士。可派遣刺殺敵將，成功率隨 INT 提升。',
  'counter-intel':     '反間 — 反查細作。敵方間諜成功率 −50%，可植入假情報。',
  'defector-reward':   '招降 — 厚賞降將。敵將戰敗投降概率 +20%。',
  // ── Phase 3 economy ──
  'iron-tools':        '鐵具 — 鐵農具普及。農業 +20%，需 iron-mining 政策。',
  'caravan-protection':'護商 — 沿途設亭驛。商隊損失 −50%，商業 +10%。',
  'horse-trade':       '馬市 — 邊境馬市。每季新馬 +30 匹，與羌/匈奴互市。',
  'copper-mining':     '銅礦 — 開銅礦。金 +50/季，需有銅礦資源城。',
  'iron-mining':       '鐵礦 — 開鐵礦。鍛造效率 +50%，需鐵礦資源城。',
  timber:              '林業 — 林場伐木。造船/攻城器械成本 −30%。',
  'pearl-trade':       '珍珠貿 — 沿海珍珠採集。金 +60/季，需沿海城。東吳特色。',
  'jade-trade':        '玉貿 — 西域玉器貿易。金 +40，外交禮品 +1 等級。',
  corvee:              '力役 — 徵召民夫服勞役。工程速度 ×1.5，民忠 −2/季。',
  'tax-light':         '輕徭薄賦 — 減免稅賦。民忠 +5，但金收入 −20%。',
  // ── Phase 3 military ──
  'watch-towers':      '烽燧 — 邊境烽火預警。敵軍入侵預警 +1 季。',
  'garrison-rotation': '番上 — 駐軍輪換。守軍士氣 −30% 損耗，疲勞 −50%。',
  'chariot-corps':     '戰車 — 戰車軍編成。平原戰力 +20%，山地 −30%。',
  'shield-wall':       '盾陣 — 盾兵密集。受箭傷害 −30%，受魔法/火傷害 −10%。',
  'naval-fireships':   '火船 — 火攻船。水戰中可發動連環船+火攻組合，傷害 ×2。',
  'naval-rams':        '衝角 — 撞角戰術。水戰首擊傷害 +40%，可衝沉敵船。',
  'horse-armor':       '馬鎧 — 鐵騎兵。騎兵防禦 +30%，但移動 −1。',
  'mountain-stronghold': '山寨 — 山地築寨。山地城市防 +25%，可徵召山民兵。',
  // ── Phase 3 civil ──
  'household-register':'戶籍 — 編製戶口冊。稅收 +10%，徵兵效率 +20%。',
  examination:         '察舉 — 漢代察舉制。每季全國發現 1-2 名隱士。',
  'mourning-rites':    '喪禮 — 制定喪禮規格。世族忠誠 +5，但金庫 −20/季。',
  library:             '圖書 — 設置藏書閣。學者武將智力恢復 +1/季。',
  'music-bureau':      '樂府 — 採集民間樂歌。文官+魅力恢復 +1/季。',
  'school-village':    '鄉學 — 廣設鄉校。寒門武將招募 +20%，文化人口 +5%。',
  'imperial-edict':    '詔書 — 帝制下詔。聯軍可發動共同行動，士氣 +5。',
  // ── religion (civil chip) ──
  'five-emperors':     '五帝祭 — 五帝祭祀。皇族正統 +10，建國加分。',
  'mountain-spirit':   '山神祭 — 祭祀山神。山地城市忠誠 +5，山民歸附 +1。',
  'river-god':         '河神祭 — 祭祀河神。水患減半，水軍出兵時士氣 +3。',
  // ── Phase 3 diplomacy ──
  'envoy-bureau':      '鴻臚寺 — 設外交使團。可同時派 3 個使節，外交效率 +30%。',
  'frontier-market':   '邊市 — 邊境互市。異族貿易金 +50/季，但細作風險 +1。',
  'captives-ransom':   '贖俘 — 贖回戰俘。減少士氣損失，可換回被擒武將。',
  // ── Phase 4 economy ──
  'gold-mining':       '金礦 — 開金礦。每季金 +120，需金礦資源城（稀少）。',
  'forest-conservation':'護林 — 設山林禁伐區。timber 政策效率 +30%，水土流失 −1。',
  pottery:             '陶器 — 陶器作坊。商業 +5/季，民間日用品供應充足。',
  lacquerware:         '漆器 — 漆器精造。高級奢侈品出口，外交禮品 +1 等。',
  'merchant-guild':    '行會 — 建立商會。商業 +12，但商人世族影響 +1。',
  'river-customs':     '関稅 — 江河關卡。每季金 +50，水運效率 −5%。',
  'pawn-bureau':       '質庫 — 官辦當鋪。災年金 +30 (典當收入)，民忠 −1。',
  'court-treasury':    '內庫 — 帝王私帑。奢華消費可獨立，外交賞賜不耗國庫。',
  'bamboo-craft':      '竹器 — 竹器作坊。輕工業 +5%，需有竹林資源。',
  'sericulture-tax':   '桑稅 — 桑田專稅。每季金 +35，但 silk-loom 效率 −10%。',
  // ── Phase 4 military ──
  'archery-school':    '射禮 — 設射禮練弓。弓兵命中 +15%，新兵 WAR 略增。',
  'military-drill':    '演武 — 大演武。全軍士氣 +5%，戰前狀態 +1 季。',
  'supply-train':      '輜重 — 後勤輜重隊。遠征不易斷糧，糧耗 −20%。',
  'siege-tower':       '樓車 — 攻城樓車。攻城傷害 +30%，城牆耐久 −15%。',
  'engineer-corps':    '工程營 — 工程兵編制。築橋/修路/挖壕 ×2 速度。',
  'frontier-cavalry':  '邊騎 — 邊地騎兵。輕騎兵 +20% 機動，可巡邊。',
  'mountain-passes':   '關隘 — 險要設關。山地關卡防禦 +35%，需山地城。',
  watchnight:          '夜禁 — 城內宵禁。內亂概率 −30%，民忠 −1/季。',
  'spear-corps':       '槍隊 — 長槍兵團。剋制騎兵 +25%，平原戰力穩定。',
  'assault-troops':    '突擊隊 — 死士突擊隊。第一回合衝鋒傷害 +40%，但傷亡高。',
  // ── Phase 4 civil ──
  'noble-titles':      '封爵 — 賞賜爵位。武將忠誠 +10，但長期世族化加深。',
  'imperial-tour':     '巡幸 — 帝王巡幸。沿途城市民忠 +5，但奢費 ×2。',
  'charity-house':     '養濟院 — 設孤殘院。民忠 +3，瘟疫 −20%，金 −25/季。',
  mediation:           '鄉約 — 鄉里調解。內亂概率 −15%，民忠 +2。',
  'standardize-weights':'度量衡 — 統一度量。商業 +10%，稅收 +5%，內政效率 +5。',
  'standardize-script':'文字 — 統一文字。文化人口 +5%，行政效率 +10%。',
  'map-survey':        '圖經 — 全國繪圖。軍事偵察 +1 級，行軍路線優化。',
  'crime-amnesty':     '大赦 — 大赦天下。民忠 +8 (一次性)，但盜賊 +10%。',
  // ── religion (civil chip) ──
  'temple-building':   '寺廟 — 大規模建寺。民忠 +3，但金 −40/季，部分人口出家。',
  'new-year-rites':    '元正 — 元正大朝。每年初士氣 +10%，外賓必至。',
  alchemy:             '煉丹 — 道家煉丹。可採尋長生丹藥，武將壽命延長機率。',
  'soul-prayer':       '招魂 — 為陣亡士兵招魂。戰後士氣恢復 +10%。',
  // ── Phase 4 diplomacy ──
  bribery:             '收買 — 賄賂敵方官吏。敵情獲取 +30%，敵國民忠 −5%。',
  'propaganda-songs':  '童謠 — 政治童謠散布。敵國民忠每季 −1，難以追蹤源頭。',
  'nanman-tribute':    '南蠻朝貢 — 收南蠻朝貢。每季金 +40 + 象 +1，需 frontier-pacification。',
  // ── Phase 5 economy ──
  ironworks:           '鐵冶 — 國營鐵冶。武器產量 +25%，需 iron-mining 配套。',
  shipyard:            '造船廠 — 大型造船廠。每季新船 +5，水軍規模 +20%。',
  canal:               '運河 — 開鑿運河。糧運效率 ×2，金 −80 一次性建設費。',
  'water-mill':        '水車 — 水力磨坊。糧產 +12%，需河流城市。',
  weaving:             '紡織 — 國營紡織坊。商業 +8，士兵冬裝普及。',
  'silver-mining':     '銀礦 — 開銀礦。金 +90/季，需銀礦資源城（稀少）。',
  'tea-cultivation':   '茶園 — 茶樹種植。茶葉商業 +10，可外貿。',
  bridges:             '修橋 — 大規模建橋。行軍速度 +10%，水運便利。',
  caravansary:         '驛館 — 沿途館驛。商旅疲勞 −50%，商業 +5%。',
  'river-dredging':    '浚河 — 定期疏浚河道。洪災 −50%，水運效率 +15%。',
  'horse-breeding':    '牧苑 — 國家牧場。每季新馬 +50 匹，騎兵補充加速。',
  'famine-loans':      '借糧 — 凶年借糧。災年民忠不下滑，金 −60 借出。',
  // ── Phase 5 military ──
  'skirmish-corps':    '散兵 — 散兵騷擾。森林伏擊 +20%，但正面戰力低。',
  'light-cavalry':     '輕騎 — 輕騎偵察。情報範圍 +1 城，騎兵機動 +1。',
  'bandit-suppression': '剿匪 — 剿匪安境。山賊 −80%，治安 +20%，民忠 +3。',
  'pirate-suppression': '剿海寇 — 剿沿海寇。沿海安全 +25%，商業 +10%。',
  'veteran-pension':   '退伍 — 老兵養贍。武將自然死亡 −10%，士兵忠誠 +5%。',
  'military-academy':  '武備學堂 — 武官學堂。每季新生武將 WAR/LED +5。',
  'moat-construction': '護城河 — 環城護城河。城防 +20%，攻城方傷亡 +25%。',
  'camp-discipline':   '軍紀 — 嚴明軍紀。士兵不擾民，民忠 +3，將士忠誠 +10。',
  'river-watchtower':  '江樓 — 江邊瞭望樓。江岸敵情早警 +1 季。',
  'coastal-fortress':  '海防 — 沿海要塞。海上入侵防禦 +30%，海寇 −50%。',
  // ── Phase 5 civil ──
  'six-ministers':     '三公九卿 — 中央官制改革。行政效率 +25%，世族影響 +1。',
  protocol:            '朝儀 — 朝堂禮儀。外交禮節 +1 等，朝臣不亂禮。',
  'royal-physicians':  '太醫 — 設太醫署。皇帝/重臣壽命延長機率，瘟疫 −20%。',
  'imperial-guard':    '禁衛 — 皇宮禁衛。京城叛亂幾乎不可能，金 −30/季。',
  'official-promotion': '升遷 — 正規升遷制度。武將升職速度 +20%。',
  'royal-park':        '苑囿 — 皇家園林。皇族享樂，民忠 −3，奢費 +50/季。',
  'prefecture-reform': '郡縣改革 — 重劃郡縣。內政效率 +15%，地方影響 −1。',
  'land-survey':       '計畝 — 全國丈量田畝。稅收 +15%，民忠 −2（豪族抵制）。',
  // ── religion (civil chip) ──
  'sky-altar':         '圜丘 — 圜丘祭天。帝制正統 +15，建國儀禮 +1 等。',
  'earth-altar':       '方丘 — 方丘祭地。豐收禱告，農業 +5%。',
  'mountain-pilgrimage': '朝山 — 五嶽朝山。聖山城市忠誠 +5，可培養道士。',
  'ancestral-temple':  '太廟 — 太廟祭祀。皇族忠誠 +15，子孫合法繼承。',
  // ── Phase 5 frontier diplomacy ──
  'xianbei-buffer':    '鮮卑緩衝 — 邊境設緩衝區。鮮卑入侵 −60%，邊境 horse-trade +。',
  'xiongnu-tribute':   '匈奴朝貢 — 匈奴稱臣納貢。每季金 +30 + 馬 +20。',
  'qiang-pacification': '羌族安撫 — 撫西涼羌族。叛亂 −70%，可徵羌騎。',
  'wuhuan-buffer':     '烏桓緩衝 — 治理烏桓。東北邊境 +50% 穩定。',
  'jiao-pacification': '交州安撫 — 安南越族。南方城市 +5 民忠，可開南海貿易。',
  'liaodong-buffer':   '遼東緩衝 — 公孫氏邊境。遼東叛亂 −80%。',
};

const CATEGORIES: CatalogCategory[] = [
  { key: 'economy',   zh: '民政', en: 'Economy',   color: '#b8c87a' },
  { key: 'civil',     zh: '文教', en: 'Civil',     color: '#88b7e8' },
  { key: 'military',  zh: '兵備', en: 'Military',  color: '#b8442e' },
  { key: 'diplomacy', zh: '外交', en: 'Diplomacy', color: '#d4a84a' },
];

interface Props { onClose: () => void; }

export function PoliciesModal({ onClose }: Props) {
  const items: CatalogItem[] = Object.entries(POLICY_DEFS).map(([id, def]) => ({
    id,
    zh: def.zh,
    en: def.en,
    description: POLICY_DESC[id] ?? '',
    category: POLICY_CATEGORY[id] ?? 'civil',
  }));
  return (
    <CatalogModal
      onClose={onClose}
      title={{ zh: '政策', en: 'Policies' }}
      items={items}
      categories={CATEGORIES}
    />
  );
}
