import { TACTIC_DEFS, tacticBonus, isTacticSignature } from '../../game/data/officerAttributes';
import { CatalogModal, type CatalogItem, type CatalogCategory } from './CatalogModal';

function bonusBadge(id: string): string {
  const b = tacticBonus(id);
  const parts: string[] = [];
  if (b.war) parts.push(`武+${b.war}`);
  if (b.leadership) parts.push(`統+${b.leadership}`);
  if (b.intelligence) parts.push(`知+${b.intelligence}`);
  if (b.politics) parts.push(`政+${b.politics}`);
  if (b.charisma) parts.push(`魅+${b.charisma}`);
  const sig = isTacticSignature(id) ? '★ ' : '';
  return sig + parts.join(' ');
}

// Classify 24 tactics into 4 categories.
const TACTIC_CATEGORY: Record<string, string> = {
  charge:         'melee',
  rouse:          'melee',
  ambush:         'melee',
  'last-stand':   'melee',
  'iron-wall':    'melee',
  rush:           'melee',
  volley:         'ranged',
  crossbow:       'ranged',
  catapult:       'ranged',
  'fire-arrow':   'ranged',
  meteor:         'ranged',
  'fire-attack':  'mystic',
  'water-attack': 'mystic',
  thunder:        'mystic',
  'borrow-wind':  'mystic',
  'eight-gates':  'mystic',
  ruse:           'disrupt',
  disorder:       'disrupt',
  pitfall:        'disrupt',
  curse:          'disrupt',
  beauty:         'disrupt',
  chain:          'disrupt',
  'self-injury':  'disrupt',
  retreat:        'disrupt',
  feint:          'strategy',
  'besiege-wei':  'strategy',
  'wait-tired':   'strategy',
  'sneak-cross':  'strategy',
  'probe-snake':  'strategy',
  'lure-tiger':   'strategy',
  'loose-catch':  'strategy',
  'kill-king':    'strategy',
  'cut-supply':   'strategy',
  cicada:         'strategy',
  'far-near':     'strategy',
  'borrow-arrow': 'ranged',
  'deceive-sky':  'strategy',
  'loot-fire':    'strategy',
  'from-nothing': 'strategy',
  'watch-fire':   'strategy',
  'hide-knife':   'disrupt',
  'brick-jade':   'strategy',
  'muddy-fish':   'strategy',
  'door-thief':   'strategy',
  'tree-flower':  'disrupt',
  'guest-host':   'strategy',
  'feign-mad':    'disrupt',
  'pull-ladder':  'strategy',
  'borrow-knife': 'disrupt',
  'lead-sheep':   'strategy',
  'borrow-corpse':'strategy',
  'plum-peach':   'strategy',
  'borrow-road':  'strategy',
  'switch-beam':  'disrupt',
  'point-curse':  'disrupt',
  'plum-thirst':  'melee',
  'seven-lamp':   'mystic',
  'chu-songs':    'disrupt',
  'burn-bowang':  'mystic',
  'wooden-ox':    'strategy',
  'hair-head':    'strategy',
  'white-robe':   'disrupt',
  'song-map':     'strategy',
  'seven-grab':   'strategy',
  'tongue-war':   'strategy',
  changban:       'melee',
  'zhuge-bow':    'ranged',
  'chain-ship':   'strategy',
  'burn-yiling':  'mystic',
  'know-self':    'strategy',
  'fast-strike':  'melee',
  deception:      'disrupt',
  'attack-plans':   'strategy',
  'attack-heart':   'strategy',
  'surround-three': 'strategy',
  'subdue-no-fight':'strategy',
  'hide-light':     'strategy',
  'total-victory':  'strategy',
  'water-form':     'strategy',
  'ortho-extra':    'strategy',
  'qimen-dunjia':   'mystic',
  'star-prayer':    'mystic',
  'he-luo-tu':      'mystic',
  'five-thunder':   'mystic',
  'sneak-yinping':  'strategy',
  'nine-campaigns': 'strategy',
  'xiling-stand':   'melee',
  'feign-illness':  'disrupt',
  'iron-chain':     'ranged',
  'two-tigers':     'disrupt',
  'lure-tiger-wolf':'disrupt',
  'sow-discord-2':  'disrupt',
  'thousand-ride':  'melee',
  'lone-blade':     'melee',
  'pass-six':       'melee',
  'burn-xinye':     'mystic',
  'solid-camp':     'strategy',
  'death-ground':   'melee',
  'siege-relief':   'strategy',
  bloodless:        'strategy',
  // ── Phase 60 ──
  'plan-war':       'strategy',
  'cavalry-war':    'melee',
  'naval-war':      'ranged',
  'trust-war':      'strategy',
  'many-war':       'strategy',
  'few-war':        'strategy',
  'mountain-war':   'strategy',
  'night-war':      'disrupt',
  'supply-war':     'strategy',
  'defend-war':     'melee',
  'fire-ox':        'mystic',
  'sand-dam':       'mystic',
  'ban-chao':       'melee',
  'mass-burial':    'melee',
  'long-ride':      'melee',
  surprise:         'disrupt',
  unguarded:        'disrupt',
  'wind-forest':    'melee',
  'quick-decision': 'melee',
  protracted:       'strategy',
  'warm-wine':      'melee',
  'three-fight-lubu':'melee',
  'plum-wine':      'strategy',
  longzhong:        'strategy',
  'burn-chibi':     'mystic',
  'lose-jingzhou':  'disrupt',
  'flee-maicheng':  'melee',
  'white-emperor':  'strategy',
  'tearful-ma':     'strategy',
  'wuzhang-star':   'mystic',
  memorial:         'strategy',
  'edict-belt':     'disrupt',
  'borrow-jingzhou':'strategy',
  diaochan:         'disrupt',
  'liu-bei-share-meat':'strategy',
  'no-clash':       'strategy',
  'mind-might':     'strategy',
  'reverse-encircle':'melee',
  'flower-bloom':   'melee',
  annihilate:       'melee',
  attrition:        'strategy',
  'scorched-earth': 'strategy',
  'siege-starve':   'strategy',
  'break-encircle': 'melee',
  'bait-trap':      'disrupt',
  'encircle-no-attack':'strategy',
  'heart-war':      'strategy',
  'counter-plot':   'disrupt',
  'press-pursuit':  'melee',
  'still-vs-motion':'strategy',
  // ── Phase 61 ──
  'plan-state':         'strategy',
  'assess-enemy':       'strategy',
  'govern-troops':      'strategy',
  'on-generalship':     'strategy',
  'adapt-change':       'strategy',
  'inspire-soldiers':   'strategy',
  'benevolence-root':   'strategy',
  'emperor-duty':       'strategy',
  'set-ranks':          'strategy',
  'strict-position':    'strategy',
  'use-many':           'strategy',
  'five-virtues':       'strategy',
  'authority-war':      'strategy',
  'know-nature':        'strategy',
  'when-not-fight':     'strategy',
  'observe-general':    'strategy',
  'eagle-strike':       'melee',
  'tiger-crouch':       'melee',
  'leopard-wolf':       'melee',
  'crane-chickens':     'melee',
  'snake-rat':          'disrupt',
  'bee-swarm':          'melee',
  'ant-siege':          'melee',
  'whale-silk':         'strategy',
  'half-cross':         'melee',
  'array-wait':         'melee',
  'conserve-strength':  'strategy',
  'high-ground':        'melee',
  'mountain-back':      'strategy',
  'intercept-relief':   'melee',
  'rush-supply':        'disrupt',
  'feign-defeat':       'disrupt',
  'set-ambush-path':    'disrupt',
  'quick-night':        'disrupt',
  'star-reading':       'mystic',
  'tortoise-shell':     'mystic',
  'elements-counter':   'mystic',
  talisman:             'mystic',
  'summon-spirits':     'mystic',
  'julu-battle':        'melee',
  'muye-battle':        'melee',
  'chengpu-battle':     'strategy',
  'hanzhong-battle':    'melee',
  'lose-jieting':       'strategy',
  'zhao-yun-baby':      'melee',
  'huang-zhong-dingjun':'melee',
  'zhou-yu-plan':       'strategy',
  'seek-talent':        'strategy',
  'he-jin-blunder':     'disrupt',
  // ── Phase 62 (100 new) ──
  'form-squads': 'strategy', 'drill-troops': 'strategy', 'march-camp': 'strategy',
  'field-camp': 'strategy', 'inspect-army': 'strategy', 'train-officers': 'strategy',
  'use-blade': 'melee', 'short-long': 'melee', 'firearm-tactics': 'ranged',
  'banner-signals': 'strategy', 'cart-camp': 'strategy', 'wolf-claw': 'melee',
  'combat-awe': 'strategy', 'attack-authority': 'strategy', 'defense-authority': 'strategy',
  'general-command': 'strategy', 'soldier-command': 'strategy',
  'upper-strategy': 'strategy', 'middle-strategy': 'strategy', 'lower-strategy': 'strategy',
  'orth-extra-use': 'strategy', 'tang-li-arts': 'strategy',
  'fan-lihua': 'mystic', 'mu-guiying': 'mystic', mulan: 'melee',
  'sun-shangxiang': 'melee', 'huang-yueying': 'strategy', 'lu-lingqi': 'melee',
  'ma-yunlu': 'disrupt', 'lady-zhurong-tac': 'melee',
  'beans-to-soldiers': 'mystic', 'ride-clouds': 'mystic', 'wind-walk': 'mystic',
  'mist-shroud': 'mystic', 'jade-edict': 'mystic', 'summon-gods': 'mystic',
  'multi-body': 'mystic', 'gate-of-life': 'mystic',
  'royal-way': 'strategy', 'daoist-wuwei': 'strategy', 'legalist-strict': 'strategy',
  'mohist-defense': 'strategy', 'diplomat-debate': 'strategy', 'yinyang-divine': 'mystic',
  'confucian-rite': 'strategy', 'strategist-way': 'disrupt',
  'qi-cart-camp': 'strategy', 'yu-wolf-claw': 'melee', 'yuan-ningyuan': 'melee',
  'sun-guanning': 'strategy', 'zheng-taiwan': 'strategy', 'dorgon-pass': 'melee',
  'zuo-xinjiang': 'strategy', 'lin-anti-opium': 'strategy', 'nian-rebellion': 'melee',
  'wu-sangui': 'disrupt',
  'retreat-no-block': 'strategy', 'desperate-no-pursue': 'strategy',
  'siege-leave-gap': 'strategy', 'no-uphill-attack': 'strategy',
  'no-hillback-fight': 'strategy', 'no-bait-take': 'strategy',
  'no-elite-attack': 'strategy', 'half-formed-no-strike': 'strategy',
  'avoid-strong-strike-weak': 'strategy', 'silent-killer': 'strategy',
  'feign-coward': 'disrupt', 'lone-wolf': 'melee',
  'peach-garden-tac': 'strategy', 'whip-postman': 'melee', 'protect-people': 'strategy',
  'sun-quan-bow': 'melee', 'mi-fang-betray': 'disrupt', 'wei-yan-back': 'disrupt',
  'guan-yu-pardon': 'strategy', 'zhang-fei-poker': 'disrupt',
  'eight-immortals': 'mystic', 'phoenix-rise': 'mystic', 'dragon-claw': 'mystic', 'turtle-shell': 'mystic',
  'xiongnu-raid': 'melee', 'qiang-horse': 'ranged', 'wuhuan-mounted-tac': 'melee',
  'shanyue-mountain': 'disrupt', 'wuge-rattan-tac': 'melee',
  'yellow-turban-mob': 'melee', 'black-mountain-bandit': 'melee', 'water-bandit': 'ranged',
  'sworn-brothers': 'strategy', 'rebel-uprising': 'strategy',
  // ── Phase 63 (100 new) ──
  'twin-spear': 'melee', 'long-halberd': 'melee', 'twin-axe': 'melee',
  'short-blade': 'melee', 'long-whip': 'melee', 'meteor-hammer': 'melee',
  'hidden-weapon': 'disrupt', 'bagua-palm': 'melee', 'whip-13': 'melee',
  'iron-sand-palm': 'melee', 'flying-knife': 'ranged', 'duck-axe': 'melee',
  'crescent-shovel': 'melee', 'hand-hook': 'melee', 'iron-pipa': 'disrupt',
  'yi-jin-jing': 'mystic', 'xi-sui-jing': 'mystic', 'nine-yin': 'mystic',
  'nine-yang': 'mystic', 'turtle-breath': 'mystic', 'iron-shirt': 'melee',
  'golden-bell': 'melee', 'vajra-finger': 'melee', 'crane-stance': 'melee',
  'child-kungfu': 'melee',
  'caesar-cross': 'strategy', 'napoleon-flank': 'strategy', 'hannibal-cannae': 'strategy',
  'macedonian-phalanx': 'melee', 'mongol-whirlwind': 'melee', 'viking-raid': 'melee',
  'roman-legion': 'melee', 'english-longbow': 'ranged', 'greek-fire': 'mystic',
  'spartan-300': 'melee',
  'heavy-cav': 'melee', 'light-cav': 'melee', 'sniper-bow': 'ranged',
  'repeat-crossbow-cart': 'ranged', 'siege-tower': 'melee', 'fire-boat': 'mystic',
  'heavy-foot': 'melee', 'three-stage': 'strategy', 'wandering-knight': 'melee',
  'death-squad': 'melee', 'honor-guard': 'melee', 'mountain-militia': 'strategy',
  'mixed-barbarian': 'strategy', 'boy-soldier': 'strategy', 'veteran-cohort': 'melee',
  'burn-talisman': 'mystic', 'five-thunder-roof': 'mystic', 'soul-snatch': 'mystic',
  'gu-poison': 'mystic', 'wood-puppet': 'mystic', 'reverse-soul': 'mystic',
  'long-sound': 'mystic', 'mind-link': 'mystic', 'geomancy-formation': 'mystic',
  'maoshan-rite': 'mystic',
  'faction-manipulate': 'strategy', 'regent-power': 'strategy', 'depose-elder': 'strategy',
  'imperial-inlaw': 'strategy', 'eunuch-power': 'strategy', 'false-edict': 'disrupt',
  'court-debate': 'strategy', 'petition-campaign': 'strategy', 'rumor-spread': 'disrupt',
  'smear-opponent': 'disrupt',
  'wang-lang-cursed': 'strategy', 'pang-de-coffin': 'melee', 'six-expeditions': 'strategy',
  'sima-eight': 'strategy', 'le-jin-raid': 'disrupt', 'zhang-liao-xiaoyao': 'melee',
  'gan-ning-100': 'melee', 'taishi-ci-vs-sunce': 'melee', 'zhao-yun-courage': 'melee',
  'ma-chao-han-sui': 'disrupt', 'huang-gai-fake': 'disrupt', 'zhou-cang-blade': 'melee',
  'wuchao-grain': 'mystic', 'cao-cao-mengjin': 'strategy', 'lu-bu-yuan-gate': 'ranged',
  'iron-guard': 'melee', 'ballista-emplace': 'ranged', 'feather-arrow': 'ranged',
  'chain-mail-foot': 'melee', 'wooden-ox-mk2': 'strategy', 'zhuge-bow-mk2': 'ranged',
  'thousand-arrows': 'ranged', 'chain-machines': 'strategy', 'fire-crow': 'mystic',
  'one-nest-bees': 'mystic', 'sky-fire-crow': 'mystic', 'cannon-man-slayer': 'ranged',
  'red-cannon': 'ranged', 'iron-cart-train': 'strategy', 'flame-thrower': 'mystic',
  // ── Phase 64 (200 new — bulk classification) ──
  zhuolu:'strategy', dazexiang:'strategy', 'chu-han':'strategy', 'mobei-battle':'melee',
  feishui:'strategy', 'sui-chen':'strategy', xuanwumen:'disrupt', anshi:'strategy',
  huangchao:'strategy', chanyuan:'strategy', jingkang:'strategy', 'fishing-castle':'melee',
  'mongol-song':'melee', 'poyang-lake':'mystic', tumu:'disrupt', 'beijing-defense':'melee',
  'wanli-three':'strategy', sarhu:'melee', ningjin:'ranged', 'yangzhou-ten':'melee',
  'jiading-three':'melee', 'three-feudatories':'strategy', yaksa:'melee', 'ulan-butong':'melee',
  'mengjin-cross':'strategy', 'mawei-slope':'melee', 'dingjun-mtn':'melee', 'jieting-loss':'strategy',
  'wuzhang-fall':'mystic', 'jincheng-defend':'melee', 'shangfang-valley':'mystic', 'yiling-fire':'mystic',
  'hefei-defense':'melee', 'jiameng-pass':'melee', 'xiapi-flood':'mystic', 'jingzhou-fall':'disrupt',
  'fancheng-flood':'mystic', 'changban-bridge':'melee', 'guandu-grain':'mystic', 'red-cliffs-wind':'mystic',
  'han-xin-count':'strategy', 'xiang-yu-horse':'melee', 'fan-li-retire':'strategy', 'lian-po-thorn':'strategy',
  'zhao-she-vs-zhao':'strategy', 'wang-jian-six':'strategy', 'zhou-yafu':'strategy', 'wei-qing-north':'melee',
  'ban-chao-far':'melee', 'ma-yuan-coffin':'melee', 'deng-yu-zhongxing':'strategy', 'kou-xun-henei':'strategy',
  'feng-yi-cart':'melee', 'du-yu-bamboo':'strategy', 'xie-xuan-8k':'melee', 'liu-yu-north':'melee',
  'wei-rui-liang':'melee', 'yang-su-chen':'melee', 'han-qinhu-cross':'melee', 'li-jing-turk':'melee',
  'guo-ziyi-lone':'melee', 'yue-fei-yan':'melee', 'han-shizhong-water':'ranged', 'wu-jie-mtn':'melee',
  'meng-gong-defend':'melee', 'zhang-shijie-naval':'ranged', 'qi-jiguang-wokou':'melee', 'yu-dayou-fujian':'melee',
  'li-rusong-korea':'melee', 'song-yingchang-korea':'strategy', 'mao-wenlong-pidao':'melee', 'lu-xiangsheng':'melee',
  'sun-chuanting-tang':'melee', 'shi-kefa-yangzhou':'melee', 'zheng-zhilong-sea':'ranged', 'liu-mingchuan-taiwan':'strategy',
  'feng-zicai-zhennan':'melee', 'nie-shicheng-tianjin':'melee', 'duan-qirui-anhui':'strategy', 'feng-yuxiang-xian':'strategy',
  'jin-school':'strategy', 'han-school':'strategy', 'wu-school':'ranged', 'shu-school':'strategy',
  'wei-school':'melee', 'yue-school':'mystic', 'qin-school':'melee', 'chu-school':'mystic',
  'qi-school':'strategy', 'yan-school':'melee', 'mongol-school':'melee', 'persian-school':'ranged',
  'japan-school':'melee', 'korean-school':'ranged', 'india-school':'mystic', 'tibet-school':'mystic',
  'manchu-school':'melee', 'tangut-school':'melee', 'jurchen-school':'melee', 'khitan-school':'melee',
  'lubu-flying':'melee', 'guanyu-greendragon':'melee', 'zhangfei-yelling':'melee', 'zhaoyun-shadow':'melee',
  'machao-spear':'melee', 'huangzhong-bow':'ranged', 'weiyan-charge':'melee', 'jiangwei-disciple':'strategy',
  'caocao-poetry':'strategy', 'xiahoudun-eye':'melee', 'dianwei-double-axe':'melee', 'xuchu-iron-fist':'melee',
  'zhanghe-mobility':'melee', 'zhanglao-ambush':'disrupt', 'panghong-sleep':'disrupt', 'simayi-tortoise':'strategy',
  'sunce-blade':'melee', 'sunquan-blue-eye':'strategy', 'zhouyu-music':'mystic', 'lumeng-study':'strategy',
  'luxun-fire':'mystic', 'taishici-arch':'ranged', 'huanggai-old':'disrupt', 'gan-ning-bell':'melee',
  'zhuge-fan':'strategy', 'pang-tong-chain':'mystic', 'fazheng-strategy':'strategy', 'huangzhong-old-bow':'ranged',
  'jiang-ji-loyalty':'strategy', 'wenping-shield':'melee', 'yuejin-light':'melee', 'lidian-scholar':'strategy',
  'liu-bei-tears':'strategy', 'sun-jian-tiger':'melee', 'yuan-shao-noble':'strategy', 'yuan-shu-jade':'strategy',
  'gongsun-zan-white':'melee', 'dong-zhuo-tyrant':'disrupt', 'wang-yun-plot':'disrupt', 'cao-zhi-poem':'strategy',
  'tunnel-warfare':'melee', 'pontoon-bridge':'strategy', 'mining-walls':'melee', 'gate-tower':'melee',
  'arrow-tower':'ranged', 'wall-corner':'melee', 'moat-deep':'melee', caltrops:'disrupt',
  'ballista-tower':'ranged', 'fire-arrow-tower':'mystic', 'cauldron-oil':'mystic', 'rolling-logs':'melee',
  'spike-pit':'disrupt', 'iron-stakes':'disrupt', 'observation-tower':'strategy',
  'fake-letter':'disrupt', 'planted-spy':'disrupt', 'reverse-spy':'disrupt', 'turn-defector':'disrupt',
  'morale-collapse':'disrupt', 'banner-burn':'disrupt', 'name-call':'disrupt', 'mass-execution':'disrupt',
  'mercy-show':'strategy', 'hostage-display':'disrupt', 'public-feast':'strategy', 'rumor-defection':'disrupt',
  'shame-disgrace':'disrupt', 'ancestor-mock':'disrupt', 'family-threat':'disrupt',
  'salt-monopoly':'strategy', 'iron-monopoly':'strategy', 'tea-trade':'strategy', 'silk-road':'strategy',
  'mint-coin':'strategy', 'tax-cut':'strategy', 'land-reform':'strategy', 'merchant-tax':'strategy',
  'tribute-system':'strategy', 'forge-currency':'disrupt',
  'spy-network':'disrupt', 'double-agent':'disrupt', 'sleeper-cell':'disrupt', 'dead-drop':'disrupt',
  'fake-defector':'disrupt', 'court-bribery':'disrupt', 'maid-spy':'disrupt', 'letter-intercept':'disrupt',
  'signal-flag':'strategy', 'carrier-pigeon':'strategy',
  'sun-ce-mirror':'mystic', 'cao-rui-vase':'strategy', 'liu-shan-stupid':'strategy', 'da-qiao-marriage':'strategy',
  'dong-zhuo-fat':'strategy', 'lu-zhi-master':'strategy', 'cai-yong-lute':'mystic', 'mi-heng-drum':'disrupt',
  'zhang-jiao-yellow':'mystic', 'zhang-lu-rice':'mystic',
};

export const TACTIC_DESC: Record<string, string> = {
  charge:         '突擊 — 騎兵衝鋒突破敵陣。對未防禦的密集步兵殺傷尤甚。',
  rouse:          '鼓舞 — 提振士氣，使己方部隊一回合內 +20% 戰力。',
  ambush:         '急襲 — 出其不意，繞至敵後造成 25% 額外傷害。',
  volley:         '齊射 — 弓兵集體射擊，遠程齊發。對輕甲尤其有效。',
  crossbow:       '連弩 — 連發弩箭，穿透重甲。射程 +1。',
  catapult:       '投石 — 巨石投擲，攻城專用。對城牆造成額外損害。',
  'fire-attack':  '火計 — 火攻燒營，乘風縱火。順風時威力 +35%。',
  'water-attack': '水計 — 掘堤淹城，水攻陣地。要求臨水城池。',
  ruse:           '偽計 — 詐降詐敗誘敵深入，敵 INT <70 時必中。',
  disorder:       '撹亂 — 散布謠言使敵軍陷入混亂，−1 行動點。',
  pitfall:        '落穴 — 設伏陷阱，林地 / 山地專用，造成數倍傷害。',
  curse:          '罵聲 — 陣前痛罵激怒對方主將，引發魯莽行動。',
  // ── Phase 54 expansion ──
  'last-stand':   '死戰 — 兵力降至 30% 以下時觸發。武力 +30，自損 −20%。背水一戰之勢。',
  'iron-wall':    '鐵壁 — 重甲列陣，全員防御 +50%。對近戰傷害減半，但機動 −2。',
  rush:           '突進 — 騎兵兩段衝鋒。第一回合移動 +2，貫穿後排弱兵。',
  'fire-arrow':   '火矢 — 弓箭裹油點燃。命中時 30% 機率使目標 burning 3 回合。',
  meteor:         '流星 — 巨石抛射，落點殺傷一片。+20% 範圍傷害，攻城傷害翻倍。',
  thunder:        '雷震 — 道家雷法。命中目標暈眩 1 回合（−1 AP），對甲胄單位效果加倍。',
  'borrow-wind':  '借東風 — 七星壇求風，秋冬之季可成。次 2 回合內天氣強制為東風強勁。',
  'eight-gates':  '八門遁甲 — 道家陣門遁形。己方一回合內隱形難擊中，順便驅散敵方所有 buff。',
  beauty:         '美人計 — 美人遣往敵陣。敵將魅力 <70 時，10% 機率倒戈到我方。',
  chain:          '連環計 — 多重計策串接，破陣後敵全軍受三段 debuff（−攻 / −防 / −士氣）。',
  'self-injury':  '苦肉計 — 黃蓋詐降之術。犧牲己方一員，敵主將被引入致命陷阱。',
  retreat:        '走為上 — 安全撤退。我方部隊 0 損失退出戰場，但放棄當前目標。',
  // ── Phase 55: 三十六計 ──
  feint:          '聲東擊西 — 攻其無備。一回合內擾亂敵防線，使其判斷錯誤，主攻方向 +30% 傷害。',
  'besiege-wei':  '圍魏救趙 — 攻其必救。對敵主城施壓，引敵回援，解我方城被圍之困。',
  'wait-tired':   '以逸待勞 — 養精蓄銳。一回合不動，下回合所有反擊傷害 +50%。',
  'sneak-cross':  '暗渡陳倉 — 明修棧道暗渡之計。看似強攻一處，實則從未防之側突入。',
  'probe-snake':  '打草驚蛇 — 試探敵情。揭示敵下回合所有行動意圖。',
  'lure-tiger':   '調虎離山 — 誘使敵主力出城。敵守將 War ≥ 85 時優先離開原位。',
  'loose-catch':  '欲擒故縱 — 七擒之術。佯敗誘敵深入，敵追擊時觸發致命反伏。',
  'kill-king':    '擒賊擒王 — 直取主將。突襲敵主將，無視前排（要求 War ≥ 90）。',
  'cut-supply':   '釜底抽薪 — 斷其糧道。敵兵每回合自損 5%，持續 3 回合。',
  cicada:         '金蟬脫殼 — 偽裝替身脫身。我方留下虛位，主力悄然轉移。',
  'far-near':     '遠交近攻 — 範睢戰國之計。+30% 與遠方勢力建交成功率，鄰國敵意 +10。',
  'borrow-arrow': '草船借箭 — 諸葛之妙。霧天用草船誘敵射箭，反獲敵箭萬支，下回合弓兵 +50%。',
  'deceive-sky':  '瞞天過海 — 大智若愚之術。明擺於眾目，反而被忽略。本回合行動敵方視而不見。',
  'loot-fire':    '趁火打劫 — 乘敵內亂之機。敵勢力陷入叛亂 / 瘟疫時，攻擊傷害 +40%。',
  'from-nothing': '無中生有 — 虛實相生。製造假象兵力，使敵將判斷錯誤，分兵應對。',
  'watch-fire':   '隔岸觀火 — 坐山觀虎鬥。當敵國互相內戰時，本方資源每回合 +15%。',
  'hide-knife':   '笑裡藏刀 — 假意修好暗中圖之。對盟友突襲時，敵方無防備傷害 +50%。',
  'brick-jade':   '拋磚引玉 — 以小換大。捨棄一座低價值城池，換取敵主力深入後的反包圍。',
  'muddy-fish':   '渾水摸魚 — 亂中取勝。戰場混亂回合中，所有計策成功率 +25%。',
  'door-thief':   '關門捉賊 — 圍而不攻。包圍小股敵軍後，每回合敵 −10% 兵，逼降。',
  'tree-flower':  '樹上開花 — 借勢嚇敵。借盟軍旗號威懾，敵方士氣 −20%。',
  'guest-host':   '反客為主 — 漸進蠶食。在敵境內駐留 3 回合後，反過來掌控當地。',
  'feign-mad':    '假癡不癲 — 大智若愚。假裝平庸無能，使敵放鬆警惕，反擊時 War +20。',
  'pull-ladder':  '上屋抽梯 — 斷其退路。誘敵深入後切斷退路，敵全軍每回合 −15% 士氣。',
  // ── Phase 57: remaining 36-stratagems + 三國奇計 ──
  'borrow-knife': '借刀殺人 — 借敵勢力之手除敵。挑撥兩個敵國交戰，本方坐收漁利。',
  'lead-sheep':   '順手牽羊 — 乘隙取小利。途經敵境時，每回合自動奪取 5% 敵方糧草 / 兵力。',
  'borrow-corpse':'借屍還魂 — 借舊有威名復興。已亡勢力之名號可被借用，當前勢力獲 +20 民望。',
  'plum-peach':   '李代桃僵 — 棄車保帥。犧牲一員副將，主將與精銳兵力完整保全。',
  'borrow-road':  '假途伐虢 — 借道而行，順手取之。借盟友通道行軍，途中可奇襲沿途城池。',
  'switch-beam':  '偷梁換柱 — 暗中替換敵核心。摻入間諜替換敵主將參謀，敵計策全數失敗。',
  'point-curse':  '指桑罵槐 — 殺雞儆猴。處死某低階副將以儆全軍，己方所有將領 +15 忠誠。',
  'plum-thirst':  '望梅止渴 — 曹操故事。激勵口渴疲憊之兵，全軍士氣 +25%，持續 2 回合。',
  'seven-lamp':   '七星燈 — 諸葛延壽之術。年邁主將每回合恢復 1 點壽元，但失敗則立即死亡。',
  'chu-songs':    '四面楚歌 — 韓信絕招。包圍敵軍後唱其家鄉之歌，敵每回合 30% 機率部分倒戈。',
  'burn-bowang':  '火燒博望 — 諸葛初出茅廬之計。森林地形 + 風天可觸發，敵軍全軍 burning 3 回合。',
  'wooden-ox':    '木牛流馬 — 諸葛運糧器械。山地行軍時，每回合糧食消耗 −50%，可長期遠征。',
  // ── Phase 58: 三國名場面 + 孫子兵法 ──
  'hair-head':    '割髮代首 — 曹操踐麥律自罰之計。主將觸犯軍法時可選此代死，全軍忠誠 +20 + 軍紀 +30%。',
  'white-robe':   '白衣渡江 — 呂蒙取荊州之計。喬裝商隊渡江，敵守軍 100% 措手不及，奪城損失 −80%。',
  'song-map':     '張松獻圖 — 內應獻地圖之術。揭示敵境內所有城防 / 駐軍 / 糧草虛實，持續 3 回合。',
  'seven-grab':   '七擒孟獲 — 諸葛南征攻心之計。對異族 / 叛軍使用，每擒一次降伏 +25%，七次後永久歸順。',
  'tongue-war':   '舌戰群儒 — 諸葛說服東吳之術。主將魅力 / 智力 ≥85 時，可使中立勢力參戰己方。',
  changban:       '長坂單騎 — 趙雲救主之勇。兵力 <10% 時，主將自動突圍救出友軍，0 損失脫戰。',
  'zhuge-bow':    '諸葛連弩 — 連發十矢之弩。弓兵每回合多攻 2 次，但 −30% 移動。',
  'chain-ship':   '連環船 — 龐統獻策。水軍鎖船結陣，+40% 水戰穩定性，但若被火攻則全軍覆沒。',
  'burn-yiling':  '火燒連營 — 陸遜破劉備之計。敵軍連營七百里時觸發，全軍 burning + 大規模潰敗。',
  'know-self':    '知己知彼 — 孫子曰：百戰不殆。揭示敵主將屬性 / 計策 / 兵種克制，本戰全局加成 +15%。',
  'fast-strike':  '兵貴神速 — 孫子兵法。下回合本方所有單位行動點 +1，先機制敵。',
  deception:      '兵不厭詐 — 孫子曰：兵者，詭道也。計策成功率 +20%，但失敗時敵方識破回敬反傷。',
  // ── Phase 59 ──
  'attack-plans':   '上兵伐謀 — 孫子曰：上兵伐謀，其次伐交，其次伐兵。識破敵主帥意圖時，本方計策必中。',
  'attack-heart':   '攻心為上 — 孫子之術。敵將忠誠 <60 時，本方說降成功率 +50%。',
  'surround-three': '圍三闕一 — 孫子兵法。圍城時故意留一缺口，敵軍因逃路而潰散，攻城傷亡 −40%。',
  'subdue-no-fight':'不戰而屈人之兵 — 孫子最高境界。本方軍力顯著優勢時，敵小城自動投降。',
  'hide-light':     '韜光養晦 — 六韜之術。本方隱藏實力，敵方情報失準，計策對我方失效。',
  'total-victory':  '全勝之道 — 孫子曰：全國為上，破國次之。完整奪城（不破壞）獲 +30% 民忠。',
  'water-form':     '兵形象水 — 孫子曰：兵無常勢。本方陣形每回合可自由切換，無延遲。',
  'ortho-extra':    '以正合奇勝 — 孫子曰：凡戰者，以正合，以奇勝。正面拉鋸 + 奇兵突襲，敵防 −25%。',
  'qimen-dunjia':   '奇門遁甲 — 道家排兵之法。本方部隊在地圖上隱形 1 回合，敵無法定位攻擊。',
  'star-prayer':    '諸葛禳星 — 諸葛延壽古術。年邁主將生命 +5 年（每場戰役限一次，失敗則立死）。',
  'he-luo-tu':      '河圖洛書 — 上古先天八卦。揭示天象 / 異象的全部影響，未來 3 回合占卜結果可見。',
  'five-thunder':   '五雷正法 — 道家斬妖術。直接擊殺敵方計謀型將領（INT >80），但要求己方道術士在場。',
  'sneak-yinping':  '偷渡陰平 — 鄧艾滅蜀奇兵。穿越無路之山，從後方繞至敵都，無視所有沿途守軍。',
  'nine-campaigns': '九伐中原 — 姜維北伐意志。本主將無論勝敗，士氣不下 50，可連續發動 9 次戰役。',
  'xiling-stand':   '西陵之戰 — 陸抗對抗晉軍。被多面圍攻時 +50% 守城戰力，可堅守 5 倍時間。',
  'feign-illness':  '裝病奪權 — 司馬懿閉門裝病之計。本方主將被視為失能，敵放鬆警惕後突然反擊 +60%。',
  'iron-chain':     '鐵索橫江 — 王濬破吳前奏。鐵索鎖江阻敵舟船，水路全封，3 回合內敵無法水路機動。',
  'two-tigers':     '二虎競食 — 曹操驅劉備之計。挑撥兩員猛將互鬥，至少一方陣亡。',
  'lure-tiger-wolf':'驅虎吞狼 — 曹操之術。挑唆敵國攻打另一敵國，本方 2 回合內無人來犯。',
  'sow-discord-2':  '離間挑撥 — 散布謠言離間敵君臣。敵主將與其副將忠誠各 −15。',
  'thousand-ride':  '千里走單騎 — 關羽護嫂之程。被俘武將自動逃出，且可帶走最多 2 員嫂屬。',
  'lone-blade':     '單刀赴會 — 關羽魯肅鴻門宴。單將赴敵宴可成功談判，或硬殺對方主將。',
  'pass-six':       '過五關斬六將 — 關羽歸劉之路。連續突破 6 個敵境，每關擊殺一名守將。',
  'burn-xinye':     '火燒新野 — 諸葛二度火攻。城將陷時主動焚城，敵方接收城池 −80% 資源。',
  'solid-camp':     '結硬寨打呆仗 — 曾國藩湘軍之法。圍城每回合穩步進兵 5%，3 個月內必下任何城。',
  'death-ground':   '置之死地而後生 — 孫子之術。本方兵 <20% 時，自動觸發 +40% 攻擊 + +30% 防御。',
  'siege-relief':   '圍點打援 — 圍城打援。圍住一城吸引敵救援，本方主力埋伏中途，伏擊援軍。',
  bloodless:        '兵不血刃 — 不戰而勝。對方城池民忠 <30 + 駐軍 <10% 時可直接接收，無損失。',
  // ── Phase 60 ──
  'plan-war':       '計戰 — 百戰奇法首篇。戰前完整偵察 + 演練，所有計策成功率 +25%。',
  'cavalry-war':    '騎戰 — 騎兵突擊之要。平原作戰時騎兵 +30% 衝擊力，可貫穿至後排。',
  'naval-war':      '舟戰 — 水軍指揮。江河湖海戰時主將生效，水軍戰力 +40%，登陸傷亡 −30%。',
  'trust-war':      '信戰 — 賞信罰必。本主將忠誠 ≥90 時可使全軍士氣 +20，敵離間計失效。',
  'many-war':       '眾戰 — 以多勝寡之法。兵力 >敵 1.5 倍時，攻擊 +15%，戰場效率 +25%。',
  'few-war':        '寡戰 — 以少勝多之術。兵力 <敵 50% 時，主將指揮加成 +50%，士氣不墜。',
  'mountain-war':   '山戰 — 險地用兵。山地 / 關隘地形時，防御 +50%，可設伏。',
  'night-war':      '夜戰 — 月黑風高夜襲營。夜間發動奇襲，敵軍恐慌，行動點 −1。',
  'supply-war':     '糧戰 — 兵馬未動，糧草先行。糧道暢通時持久戰能力 +100%。',
  'defend-war':     '守戰 — 堅壁清野守城法。守城傷亡 −40%，可堅守至援軍到達。',
  'fire-ox':        '火牛陣 — 田單破燕之法。牛尾繫火，奔入敵陣，破甲陣 + 燒輜重。',
  'sand-dam':       '韓信囊沙 — 濰水之戰絕計。築沙袋阻河，伏兵半渡而擊。',
  'ban-chao':       '班超三十六 — 投筆從戎之勇。36 人可擒敵國使團，外交斬首奇襲。',
  'mass-burial':    '白起坑卒 — 長平四十萬。俘虜全部坑殺，敵國恐懼士氣 −30%，但 −50 民望。',
  'long-ride':      '霍去病千里 — 漠北遠征。騎兵可長驅 6 城距離不補給，奇襲敵後方。',
  surprise:         '出其不意 — 孫子心法。攻其未防之地，敵守軍 −60% 防御。',
  unguarded:        '攻其無備 — 趁敵不備。敵在內政 / 移動時發起攻擊，傷害 +35%。',
  'wind-forest':    '風林火山 — 速、靜、烈、不動之四象。本主將每回合切換一態，全軍 +15% 適應力。',
  'quick-decision': '速戰速決 — 孫子曰：兵聞拙速。3 回合內結束戰鬥則民忠 +20，否則 −10。',
  protracted:       '持久戰 — 耐力之爭。本方守備時，敵每回合士氣 −5，糧消 +20%。',
  'warm-wine':      '溫酒斬華雄 — 關羽神勇之始。對 War >85 的敵將，30% 機率瞬殺。',
  'three-fight-lubu':'三英戰呂布 — 劉關張合戰。三員結義武將同陣時，可對抗任何單將。',
  'plum-wine':      '煮酒論英雄 — 曹操試劉備之術。揭示敵主將真實意圖 + 性格全部。',
  longzhong:        '隆中對 — 三分天下之策。本方擁有 3+ 個州時，外交 / 內政全 +20%。',
  'burn-chibi':     '火燒赤壁 — 周郎妙計。連環船 + 東風 + 火攻三組合時觸發，敵水軍全滅。',
  'lose-jingzhou':  '大意失荊州 — 關羽教訓。對方輕敵 (War >90 + INT <60) 時，可奇襲奪城。',
  'flee-maicheng':  '走麥城 — 末路逃亡。主將兵 <5% 時自動撤退，但忠誠 −20。',
  'white-emperor':  '白帝託孤 — 劉備傳位之術。主將臨終可指定繼承人 +50 忠誠，無權力鬥爭。',
  'tearful-ma':     '揮淚斬馬謖 — 諸葛執法。處決一員無能副將，全軍 +30 紀律，但 −5 民忠。',
  'wuzhang-star':   '五丈原星隕 — 諸葛殞落。主將陣亡時，落星象徵全軍 −50 士氣，可能潰散。',
  memorial:         '出師表 — 鞠躬盡瘁。發表後本主將忠誠 +30，全軍士氣 +25，但壽元 −2 年。',
  'edict-belt':     '衣帶詔 — 漢獻帝密旨。煽動敵國臣下叛變，敵主將忠誠 −10 + 1 員可能倒戈。',
  'borrow-jingzhou':'借荊州 — 劉備借而不還。和敵盟友協議借取領土，3 年後敵憤怒索要。',
  diaochan:         '貂蟬連環 — 美人離間。對父子 / 主從關係的兩位敵將，使其反目。',
  'liu-bei-share-meat':'推食食人 — 劉備愛兵之術。每回合主將分糧予兵，全軍忠誠 +5。',
  'no-clash':       '兵不接刃 — 不戰勝。對方士氣 <20 時自動投降。',
  'mind-might':     '將謀重於兵勇 — 智勝勇。本方主將 INT >敵主將 20 點時，戰力差不受兵力影響。',
  'reverse-encircle':'反包圍 — 假被圍實圍人。佯裝被困誘敵深入後反包圍，傷害 +50%。',
  'flower-bloom':   '中心開花 — 兵分四路圍。主力突入敵中央後四面開花，全方位攻擊。',
  annihilate:       '殲滅戰 — 不留活口。戰勝後敵軍全滅，不留俘虜，本方士氣 +20，民忠 −10。',
  attrition:        '消耗戰 — 拼國力。長期對峙，本國庫存 >敵時，每回合敵 −5% 兵。',
  'scorched-earth': '焦土戰術 — 退而焚之。撤退時焚毀城池，敵接收 −80% 資源 + −50% 民忠。',
  'siege-starve':   '圍困飢戰 — 困而餓之。圍城每回合敵 −10% 糧，糧盡時不戰自降。',
  'break-encircle': '突圍戰 — 死戰殺出。被圍時所有兵力集中突破一點，傷亡 −30%。',
  'bait-trap':      '釣餌戰術 — 引魚上鉤。故意暴露弱點誘敵深入，觸發埋伏 + 反擊 +60%。',
  'encircle-no-attack':'圍而不攻 — 兵法之上。圍而不打，待敵自亂 / 議降，無傷亡接收。',
  'heart-war':      '心戰為上 — 攻心為上之延伸。每回合敵軍可能因恐懼 / 飢餓 / 思鄉投降。',
  'counter-plot':   '將計就計 — 反向破敵。本主將 INT >敵 INT 15 點時，敵計策全部回敬反噬。',
  'press-pursuit':  '趁勢追擊 — 痛打落水狗。敵兵 <30% 時主動追擊，敵 100% 全滅。',
  'still-vs-motion':'以靜制動 — 後發制人。守備位置一回合不動，下回合所有反擊 +50%。',
  // ── Phase 61 ──
  'plan-state':       '圖國 — 吳子首篇。內政 +20% / 軍備 +15%。先治國再用兵。',
  'assess-enemy':     '料敵 — 吳起察敵之術。揭示敵 6 弱點：糧 / 兵 / 將 / 城 / 路 / 卒。',
  'govern-troops':    '治兵 — 吳子治軍之道。每回合士氣 +10，逃兵 −80%。',
  'on-generalship':   '論將 — 吳子論武將標準。主將屬性各項提升 +5。',
  'adapt-change':     '應變 — 吳子應變之術。戰場上每回合可重選陣型，無冷卻。',
  'inspire-soldiers': '勵士 — 吳子激勵之術。賞罰分明，全軍 +25% 攻擊力 1 回合。',
  'benevolence-root': '仁本 — 司馬法之首。仁愛為本，民忠 +15，敵軍士氣 −5。',
  'emperor-duty':     '天子之義 — 司馬法。代天征伐，敵國敵意 +20，但本軍正義性 +30%。',
  'set-ranks':        '定爵 — 司馬法之術。軍中爵位明確，將領忠誠 +10，指揮 +10%。',
  'strict-position':  '嚴位 — 司馬法。軍規嚴明，逃兵 0，但忠誠 −5。',
  'use-many':         '用眾 — 司馬法。10 萬以上大軍效率 +20%，後勤承載 +30%。',
  'five-virtues':     '將之五善 — 諸葛論將五德：仁 / 義 / 禮 / 智 / 信。主將齊備時所有指揮 +30%。',
  'authority-war':    '兵權 — 諸葛兵權。主將絕對指揮，副將不可違令，但個人能力 +0。',
  'know-nature':      '知人性 — 諸葛知人之術。揭示己方所有武將真實忠誠 / 性格 / 隱密。',
  'when-not-fight':   '不戰之機 — 諸葛兵法。識別不可戰之時，自動規避必敗戰役。',
  'observe-general':  '觀將 — 諸葛觀將法。揭示敵將意志 / 計策 / 心理弱點。',
  'eagle-strike':     '鷹擊長空 — 高處俯衝突襲。高地優勢時，襲擊 +35%。',
  'tiger-crouch':     '虎踞龍盤 — 險要據守。地形優越時，守軍 +50% 戰力。',
  'leopard-wolf':     '豹突狼奔 — 突擊小隊。少而精的快速突進，士兵 <2000 時 +30% 機動。',
  'crane-chickens':   '鶴立雞群 — 一人鎮萬軍。本主將 War >90 + 武將獨來時，敵眾將恐慌 −20% 攻。',
  'snake-rat':        '蛇行鼠竄 — 散兵游擊。全軍轉為小隊化，敵 AOE 攻擊 −60%。',
  'bee-swarm':        '蜂擁而上 — 人海戰術。同時多路突擊，每路傷亡分散 25%。',
  'ant-siege':        '蟻附攻城 — 雲梯雲集。攻城時兵力傷亡翻倍，但破城速度 ×3。',
  'whale-silk':       '鯨吞蠶食 — 漸進蠶食。本方每回合自動奪取敵 5% 邊境，無戰鬥。',
  'half-cross':       '半渡而擊 — 渡河奇襲。敵渡河途中發動攻擊，敵 −50% 戰力。',
  'array-wait':       '列陣以待 — 嚴陣以待。先布陣後待敵來，本方守勢 +30%。',
  'conserve-strength':'養精蓄銳 — 休整待機。一回合不戰，下次戰役全軍狀態恢復 100%。',
  'high-ground':      '居高臨下 — 山頂之利。山地戰時，所有計策成功率 +20%。',
  'mountain-back':    '背山臨水 — 進退兼具。山水陣型，被圍時 −50% 損失。',
  'intercept-relief': '截擊援軍 — 圍點打援之執行。可中途攔截敵援軍，使被圍敵孤立無援。',
  'rush-supply':      '急襲糧道 — 斷敵後勤。敵主力 3 回合內缺糧 −20% 戰力。',
  'feign-defeat':     '詐敗誘敵 — 假敗真伏。主動敗退引敵深入，觸發大規模反伏。',
  'set-ambush-path':  '設伏要道 — 兵家必爭之路。在敵必經路設伏，敵通過時 100% 重創。',
  'quick-night':      '速戰夜襲 — 月黑風高。夜戰時偷襲敵營，30% 機率俘虜敵主將。',
  'star-reading':     '占星望氣 — 觀天象識戰機。揭示下季所有異象，提前準備或迴避。',
  'tortoise-shell':   '卜筮龜甲 — 占卜決疑。本回合所有決策 +50% 成功率。',
  'elements-counter': '五行相剋 — 道家剋制論。兵種剋制下，戰力差距翻倍（金克木，水剋火…）。',
  talisman:           '護身符 — 道家法寶。主將免疫一次致命傷害，物品保留至下場戰役。',
  'summon-spirits':   '招神召將 — 道家神將術。可召喚一名已陣亡名將靈助戰 1 回合。',
  'julu-battle':      '鉅鹿之戰 — 項羽破釜沉舟。本軍兵力 1/3 而戰勝強敵，士氣 +50。',
  'muye-battle':      '牧野之戰 — 武王伐紂。對暴政敵國，敵內部 50% 倒戈。',
  'chengpu-battle':   '城濮之戰 — 晉文公退避三舍。先讓後勝，本方戰局態勢逆轉 +30%。',
  'hanzhong-battle':  '漢中之戰 — 劉備奪漢中。長期消耗後一舉破敵，戰役後民忠 +25。',
  'lose-jieting':     '街亭失守 — 馬謖之失。教訓全軍：副將自負 = 戰術失敗概率 +60%。',
  'zhao-yun-baby':    '趙雲懷主 — 長坂坡七進七出。本主將兵 <5% 時仍可帶走 1 員副將安全脫戰。',
  'huang-zhong-dingjun':'黃忠定軍山 — 老將斬夏侯淵。老年武將（>55 歲）攻擊 +30% / 致命一擊 +25%。',
  'zhou-yu-plan':     '周郎妙計 — 美人陷計。聯敵之兄弟 / 親家入局，敵陣營分裂。',
  'seek-talent':      '求賢令 — 曹操唯才是舉。本回合內全國招募成功率 +50%，無門第限制。',
  'he-jin-blunder':   '何進召董 — 引狼入室。誤召敵勢力，本國控制力崩潰。教訓：戒備引外援。',
  // ── Phase 62 ──
  'form-squads':      '束伍篇 — 戚継光新書首篇。3人組／12人陣の徹底組織化、全軍指揮効率 +30%。',
  'drill-troops':     '操練篇 — 每日操練。3 月後新兵 = 老兵，士氣 / 紀律 +20。',
  'march-camp':       '行營篇 — 行軍紮營制度。長征時行軍速度 +25%，無迷失。',
  'field-camp':       '野營篇 — 野外宿營防御。野外被夜襲幾率 −70%。',
  'inspect-army':     '校閱篇 — 定期軍演。發現弱兵 / 投機者，可篩除 5% 不忠者。',
  'train-officers':   '練將篇 — 將官培養體系。中層軍官能力 +15%。',
  'use-blade':        '用刃篇 — 兵刃使用法。所有武器加成 +10%。',
  'short-long':       '短器長用 — 短兵長持訓法。槍術近戰 +20% 殺傷。',
  'firearm-tactics':  '鳥銃篇 — 明末火器。長距離殺傷 +50%，但雨雪 −80%。',
  'banner-signals':   '揭旗篇 — 軍旗指揮。大軍可分 5 路同時行動，指揮無延遲。',
  'cart-camp':        '車營制 — 戚継光車營。戰車環陣 + 內藏火器，抗騎兵 +60%。',
  'wolf-claw':        '狼筅陣 — 俞大猷狼筅武器。對倭寇 / 海盜步兵 +40% 殺傷。',
  'combat-awe':       '戰威 — 尉繚子論威。本將威名顯赫時，敵兵恐懼，戰前 −10% 戰意。',
  'attack-authority': '攻權 — 尉繚子。攻城時所有命令絕對執行，攻擊力 +20%。',
  'defense-authority':'守權 — 尉繚子。守城時將領擁有絕對處決權，逃兵 0。',
  'general-command':  '將令 — 尉繚子。主將令出必行，副將不敢違 +30% 命中。',
  'soldier-command':  '兵令 — 尉繚子。兵卒明白命令層級，混亂中保持秩序 +25%。',
  'upper-strategy':   '上略 — 黃石公三略 (上)。以仁治軍，將士同心 +30% 忠誠。',
  'middle-strategy':  '中略 — 黃石公三略 (中)。論治國用兵之術，全國效率 +15%。',
  'lower-strategy':   '下略 — 黃石公三略 (下)。具體戰術細節，戰場決策 +20%。',
  'orth-extra-use':   '奇正之用 — 唐李問對。「以正合，以奇勝」之具體執行，戰局靈活 +35%。',
  'tang-li-arts':     '太宗武略 — 李唐用兵之道。對北方游牧族戰術 +50%。',
  'fan-lihua':        '樊梨花術 — 唐傳奇女將法術。可變化雲霧迷敵眼，敵命中率 −40%。',
  'mu-guiying':       '穆桂英陣 — 楊家天門陣破解之術。對複雜陣形剋制力 +60%。',
  mulan:              '木蘭從軍 — 女扮男裝。本主將如為女性，可隱瞞性別作戰，無歧視 buff +20%。',
  'sun-shangxiang':   '尚香擲戟 — 孫尚香投擲兵。可遠距投擲多種兵器，無視盾兵防御。',
  'huang-yueying':    '黃月英巧器 — 諸葛之妻機關術。本國發明攻城器械 +50% 效率。',
  'lu-lingqi':        '呂玲綺斷流 — 呂布之女絕招。對敵主將直接衝擊，無視前排。',
  'ma-yunlu':         '馬雲祿夜襲 — 馬超之妹。夜間騎兵奇襲 +60% 突襲效果。',
  'lady-zhurong-tac': '祝融飛刀 — 五口飛刀百步穿楊。每回合可投擲 5 把飛刀，命中即殺。',
  'beans-to-soldiers':'撒豆成兵 — 道家幻術。憑空變出 2000 假兵迷敵，敵分兵應對。',
  'ride-clouds':      '騰雲駕霧 — 道家高人之術。主將可飛越地形，無視所有路徑限制。',
  'wind-walk':        '御風行走 — 道家輕功。本將移動 +5，無視沼澤 / 河流。',
  'mist-shroud':      '變幻雲霧 — 道家遮蔽。本場戰役大霧 3 回合，敵命中 −50%。',
  'jade-edict':       '玉皇敕令 — 假傳天命。敵國民忠 −20，叛亂概率 +50%。',
  'summon-gods':      '招神召將 — 道家招神。可借古名將 (項羽 / 韓信) 助戰 1 回合。',
  'multi-body':       '化身百出 — 千身術。主將同時出現多處，敵無法定位本體。',
  'gate-of-life':     '生門開啟 — 奇門遁甲生門。被圍時 100% 找到生路逃生。',
  'royal-way':        '王道征伐 — 儒家正義之師。為正義出征時士氣 +30%，民忠 +25。',
  'daoist-wuwei':     '道家無為 — 不戰無事為勝。本國不主動攻擊時，國力每季 +10%。',
  'legalist-strict':  '法家峻法 — 商鞅之治。軍紀絕對，但 −10 民忠 +30% 戰力。',
  'mohist-defense':   '墨家非攻 — 守禦之術。城防 +50%，但禁止主動攻擊。',
  'diplomat-debate':  '縱橫家辯 — 蘇秦張儀之術。可同時派遣使節到 6 國，外交效率 +60%。',
  'yinyang-divine':   '陰陽家占 — 鄒衍五德終始。可預知敵國興衰，提前布局。',
  'confucian-rite':   '儒家禮治 — 重禮輕兵。本國禮樂興盛，文官 +15，但武備 −10。',
  'strategist-way':   '兵家詭道 — 諸子兵家正統。詭計多端，敵計策剋制 +30%。',
  'qi-cart-camp':     '戚家車營 — 抗倭專用。對水上 / 沿海戰 +40%。',
  'yu-wolf-claw':     '俞家狼筅 — 俞大猷武備。竹槍尖端布滿狼牙，對重甲 +50%。',
  'yuan-ningyuan':    '袁崇煥寧遠 — 紅夷大炮守城。重砲守城 +60% 殺傷。',
  'sun-guanning':     '孫承宗關寧 — 關寧鐵騎。北方守邊精銳 +35% 戰力。',
  'zheng-taiwan':     '鄭成功收台 — 跨海登陸戰。海戰登陸 +50% 成功率。',
  'dorgon-pass':      '多爾袞入關 — 鐵騎入關。借機進攻時，騎兵衝擊 +40%。',
  'zuo-xinjiang':     '左宗棠新疆 — 抬棺出征。對遠征任務 +50% 補給能力。',
  'lin-anti-opium':   '林則徐禁煙 — 銷煙池之術。可摧毀敵國資源來源（如鹽 / 鐵）。',
  'nian-rebellion':   '捻軍騎襲 — 流動游擊戰。本軍可在敵境內遊走，敵難圍剿。',
  'wu-sangui':        '吳三桂引清 — 開關借兵。引外國勢力入境，雖速勝但 −80 民望。',
  'retreat-no-block': '歸師勿遏 — 孫子戒律。回家之兵戰意倍增，攔截傷亡 +100%，宜放行。',
  'desperate-no-pursue':'窮寇勿追 — 困獸猶鬥。窮敵反咬，追之必傷，宜放生。',
  'siege-leave-gap':  '圍師必闕 — 兵法第一守則。圍三方留一缺，敵主動逃散。',
  'no-uphill-attack': '高陵勿向 — 仰攻必敗。高地敵軍時，避免硬攻 −40% 損失。',
  'no-hillback-fight':'背丘勿逆 — 不利地形。背山逆陣，自陷不利。',
  'no-bait-take':     '餌兵勿食 — 餌中必有鉤。識破誘餌不為所動。',
  'no-elite-attack':  '銳卒勿攻 — 鋒銳難當。避其銳氣，等其疲怠。',
  'half-formed-no-strike':'半成勿擊 — 未成之陣最強。等敵布完才打反而 −30% 效果。',
  'avoid-strong-strike-weak':'避實擊虛 — 孫子心法。永遠攻敵弱點，效率 ×3。',
  'silent-killer':    '靜中取勝 — 默殺。零情報下殺敵將，全程隱身。',
  'feign-coward':     '示弱誘敵 — 表面怯懦。敵輕視深入時觸發伏擊。',
  'lone-wolf':        '孤狼戰術 — 單將深入。本主將獨自深入敵境，敵不知其虛實。',
  'peach-garden-tac': '桃園結義之力 — 三人同心。劉備關羽張飛同陣時，所有屬性 +20%。',
  'whip-postman':     '怒鞭督郵 — 張飛之怒。對腐敗官員 / 貪官敵人，可直接處決提升民望 +30。',
  'protect-people':   '攜民渡江 — 劉備仁政。撤退時保護平民，民忠 +25，但移動 −50%。',
  'sun-quan-bow':     '孫權射虎 — 君主親射。本主將親自上陣時 +30% 士氣感染。',
  'mi-fang-betray':   '糜芳投吳 — 內奸叛變。本軍可能出現叛徒，每場戰役 5% 副將倒戈。',
  'wei-yan-back':     '魏延反骨 — 性格反叛。本主將若 War >90 + 忠誠 <60，將自立。',
  'guan-yu-pardon':   '華容道義 — 關羽放曹。戰勝時可選擇釋放敵主將以換取榮譽 +50。',
  'zhang-fei-poker':  '張飛粗中有細 — 看似魯莽實則狡黠。敵以為本軍狂躁，反而中伏。',
  'eight-immortals':  '八仙過海 — 各顯神通。8 員武將同陣時，每員自動發揮獨特 skill。',
  'phoenix-rise':     '鳳凰涅槃 — 浴火重生。本主將戰死後 30% 機率復活，戰力翻倍。',
  'dragon-claw':      '神龍擺尾 — 龍尾橫掃。一次攻擊範圍 5 格，AOE 殺傷。',
  'turtle-shell':     '玄武龜甲 — 玄武神獸。被攻擊時自動 50% 化解傷害。',
  'xiongnu-raid':     '匈奴突騎 — 漠北騎兵。輕騎兵突襲 +50%，撤退無損失。',
  'qiang-horse':      '羌人騎射 — 西涼鐵騎之祖。騎射兵種戰力 +40%。',
  'wuhuan-mounted-tac':'烏丸突騎陣 — 北方蠻族騎兵。可與曹魏騎兵協同 +35%。',
  'shanyue-mountain': '山越伏擊 — 江東山林蠻族。森林 / 山地伏擊 +60%。',
  'wuge-rattan-tac':  '烏戈藤甲陣 — 兀突骨之術。藤甲兵專屬。',
  'yellow-turban-mob':'黃巾人海 — 太平道信徒。可徵召大量教徒兵，戰力 −30% 但數量 ×5。',
  'black-mountain-bandit':'黑山賊蜂起 — 張燕黑山軍。山地遊擊戰 +50%。',
  'water-bandit':     '水寇橫行 — 江湖水賊。長江 / 黃河流域水戰 +40%。',
  'sworn-brothers':   '結拜兄弟 — 異姓同袍。同陣 3+ 名結拜武將時，全員 +25% 戰力。',
  'rebel-uprising':   '揭竿而起 — 起義軍。低層民眾反抗暴政，可短時間徵召大量人數。',
  // ── Phase 63 ──
  'twin-spear':     '雙槍流 — 雙手各執一槍。攻擊次數翻倍，但 −10% 防御。',
  'long-halberd':   '長戟術 — 呂布家傳。武力 +15，可同時攻擊兩排敵兵。',
  'twin-axe':       '雙斧法 — 周泰類武。重型攻擊 +25%，破甲 +30%。',
  'short-blade':    '短刀絕技 — 近身白刃。狹窄地形 +40%，城戰專用。',
  'long-whip':      '長鞭舞 — 鞭法柔克剛。可遠距纏敵兵器，繳械幾率 +20%。',
  'meteor-hammer':  '流星錘 — 王雙之武器。每次擊中 30% 機率擊暈敵將。',
  'hidden-weapon':  '暗器手裡劍 — 飛鏢飛刀。出其不意，敵防御無視 +50%。',
  'bagua-palm':     '八卦掌 — 八卦變化。每回合自動切換攻防形態。',
  'whip-13':        '鞭法十三式 — 十三招鞭法。一回合內可連續攻擊 3 次。',
  'iron-sand-palm': '鐵砂掌 — 隔山打牛。空手戰時可造成致命傷。',
  'flying-knife':   '飛刀術 — 小李探花。命中即殺，但每場限 3 把。',
  'duck-axe':       '鴛鴦鉞 — 程咬金武。對 2 名敵同時攻擊。',
  'crescent-shovel':'月牙鏟 — 沙僧之武。攻防兼備，無短板。',
  'hand-hook':      '護手鉤 — 鉤鐮槍。對騎兵 +30% 殺傷，可勾下馬。',
  'iron-pipa':      '鐵琵琶 — 藏刀於琴。文人偽裝 +50% 隱蔽。',
  'yi-jin-jing':    '易筋經 — 達摩傳法。1 年修練後 War +20。',
  'xi-sui-jing':    '洗髓經 — 達摩內功。INT +15，神算不亂。',
  'nine-yin':       '九陰真經 — 黃裳所創。陰柔內功，反震敵攻 30%。',
  'nine-yang':      '九陽神功 — 純陽至剛。內傷自愈，戰場恢復 +50%。',
  'turtle-breath':  '龜息神功 — 假死之術。瀕死時可裝死逃生。',
  'iron-shirt':     '鐵布衫 — 抗擊打。鈍器傷害 −60%。',
  'golden-bell':    '金鐘罩 — 護體罡氣。所有外傷 −40%。',
  'vajra-finger':   '大力金剛指 — 一指破甲。可一指穿透任何盾牌。',
  'crane-stance':   '鶴翔樁 — 單腿立樁。閃避 +30%。',
  'child-kungfu':   '童子功 — 純陽不破。年輕武將 +20% 戰力。',
  'caesar-cross':   '凱撒越境 — 跨越禁地之舉。違背中央政令出兵，但 +50% 軍威。',
  'napoleon-flank': '拿破崙包抄 — 西方包抄之法。多路同時迂迴，敵陣型崩潰。',
  'hannibal-cannae':'漢尼拔坎尼 — 古典圍殲。中央誘餌 + 兩翼包圍，敵全滅。',
  'macedonian-phalanx':'馬其頓方陣 — 長矛密集。對騎兵 +60%，但機動 −60%。',
  'mongol-whirlwind':'蒙古旋風 — 騎兵高速包抄。輕騎兵速度 +50%。',
  'viking-raid':    '維京突襲 — 海岸劫掠。沿海城市突襲 +40%。',
  'roman-legion':   '羅馬軍團 — 重步兵方陣。重步兵 +25% 戰力。',
  'english-longbow':'英格蘭長弓 — 長弓射程。射程 +2，破甲 +30%。',
  'greek-fire':     '希臘火 — 拜占庭祕方。水上不熄之火，水戰 +50%。',
  'spartan-300':    '斯巴達三百 — 死守不退。300 兵以下時 +200% 戰力。',
  'heavy-cav':      '重甲鐵騎 — 鐵騎重裝。對輕步兵 +50%，但對長槍 −30%。',
  'light-cav':      '輕騎突擊 — 輕快機動。輕騎兵移動 +3，迂迴攻擊。',
  'sniper-bow':     '神弓隊 — 精選弓手。對敵將狙殺 +30%。',
  'repeat-crossbow-cart':'連弩車 — 機關連發。每回合射 5 次。',
  'siege-tower':    '攻城塔陣 — 重型攻城。城牆等級 −2。',
  'fire-boat':      '火攻船陣 — 火船突進。水戰時 +60% 火攻。',
  'heavy-foot':     '鐵塔重步 — 重甲步兵塔。防御 +50%，移動 −2。',
  'three-stage':    '弓馬槍三段 — 三段協同。弓兵 + 騎兵 + 槍兵協作，全 +20%。',
  'wandering-knight':'浪人遊俠 — 江湖獨行客。獨自行動時 +30% 機動。',
  'death-squad':    '死士隊 — 必死之兵。攻擊 +50%，但無法撤退。',
  'honor-guard':    '親衛精銳 — 主君近衛。主將戰死率 −90%。',
  'mountain-militia':'山民兵 — 山區土著。山地戰 +60%。',
  'mixed-barbarian':'蕃漢兵 — 中原+異族。多元化部隊，地形剋制 −50%。',
  'boy-soldier':    '童子軍 — 童兵奇襲。敵心軟不忍下手 −30% 攻擊。',
  'veteran-cohort': '老兵團 — 戰場老兵。傷亡 −40%，士氣不墜。',
  'burn-talisman':  '燒符引神 — 道家召神。可短暫請出本地神靈助戰。',
  'five-thunder-roof':'五雷轟頂 — 雷電直擊。對單一武將造成 200% 傷害。',
  'soul-snatch':    '攝魂奪魄 — 攝心術。敵主將魂飛魄散 −30% 屬性。',
  'gu-poison':      '蠱毒之術 — 南蠻祕術。中蠱武將每回合自損 5%。',
  'wood-puppet':    '木甲傀儡 — 木牛流馬之軍事化。30% 兵力用木偶替代。',
  'reverse-soul':   '反魂香 — 已死可活。陣亡武將 10% 機率復活。',
  'long-sound':     '千里傳音 — 道家傳訊術。遠距通訊即時，無情報延遲。',
  'mind-link':      '心電感應 — 主帥指揮無延遲。指揮效率 +40%。',
  'geomancy-formation':'風水佈陣 — 風水師佈陣。地形 buff +30%。',
  'maoshan-rite':   '茅山道術 — 茅山符咒。對妖鬼類敵 (黃巾 / 邪教) +50%。',
  'faction-manipulate':'黨爭操控 — 操縱黨爭。對方朝堂 −30% 效率。',
  'regent-power':   '攝政專權 — 攝政掌權。主君早亡時可代行君權。',
  'depose-elder':   '廢長立幼 — 廢嫡立庶。可改變繼承順序，但 −20 民忠。',
  'imperial-inlaw': '外戚干政 — 后族專權。婚姻政治 +50%。',
  'eunuch-power':   '宦官弄權 — 宦官集團。情報網 +40%，但臣下 −10 忠誠。',
  'false-edict':    '矯詔行事 — 假傳聖旨。可命令敵將領執行錯誤指令。',
  'court-debate':   '廷議辯論 — 朝堂辯論。INT >85 時辯倒對手獲 +50 政治。',
  'petition-campaign':'民眾請願 — 推動民意。可改變朝廷決策。',
  'rumor-spread':   '流言惑眾 — 散布謠言。敵國民忠 −15。',
  'smear-opponent': '抹黑對手 — 政治抹黑。敵主將被質疑能力 −10 屬性。',
  'wang-lang-cursed':'王朗罵死諸葛 — 反派被罵死。INT >95 時可說死敵將 (>60 歲)。',
  'pang-de-coffin': '龐德抬棺 — 死戰決心。本主將 +30% 戰力，但有戰死決心。',
  'six-expeditions':'六出祁山 — 諸葛北伐之志。對北方戰役 +30% 持久力。',
  'sima-eight':     '司馬八陣 — 反陣破陣。識破諸葛八陣圖效果。',
  'le-jin-raid':    '樂進偷襲 — 樂進奇兵。夜戰突襲 +40%。',
  'zhang-liao-xiaoyao':'張遼威震逍遙津 — 800 破 10 萬。少勝多時 +200% 戰力。',
  'gan-ning-100':   '甘寧百騎劫營 — 江東神將。100 騎可奇襲擾敵大營。',
  'taishi-ci-vs-sunce':'太史慈鬥孫策 — 神亭嶺單挑。一騎打獨鬥 +40%。',
  'zhao-yun-courage':'趙雲一身是膽 — 子龍之勇。被圍時自動觸發 −50% 損失。',
  'ma-chao-han-sui':'錦袍韓遂 — 馬超追討。對叛親敵將攻擊 +40%。',
  'huang-gai-fake': '黃蓋詐降 — 苦肉誘敵。已有 self-injury，這是進階版。',
  'zhou-cang-blade':'周倉扛刀 — 義氣護主。本主將被攻時，副將代受。',
  'wuchao-grain':   '烏巢糧倉 — 燒糧之計。一舉燒燬敵主糧倉，敵 30% 兵力潰散。',
  'cao-cao-mengjin':'曹操過孟津 — 渡河奇襲。本軍渡河時敵措手不及 +50%。',
  'lu-bu-yuan-gate':'呂布轅門射戟 — 神射調停。可在交戰兩方間調解。',
  'iron-guard':     '親軍鐵衛 — 主將禁衛。主將近側 5 格內死戰 −50% 損失。',
  'ballista-emplace':'弩砲陣地 — 大型弩砲。每回合可發射重弩，破城 +40%。',
  'feather-arrow':  '鳥羽箭隊 — 輕箭速射。速射 +50%，但破甲 −20%。',
  'chain-mail-foot':'鎖子甲步兵 — 鐵鎖甲胄。中重型步兵 +25% 戰力。',
  'wooden-ox-mk2':  '木牛流馬改 — 改良運糧。山地物資運輸 +100%。',
  'zhuge-bow-mk2':  '諸葛弩改 — 改良連弩。每回合射 4 次（原 2 次）。',
  'thousand-arrows':'連弩萬箭 — 集團射擊。大規模箭雨 AOE。',
  'chain-machines': '連環機關 — 機關連動。一台啟動，全部連動。',
  'fire-crow':      '神火飛鴉 — 明初火藥武器。射程 +3 的爆炸物。',
  'one-nest-bees':  '一窩蜂 — 集束火箭。一發 32 矢連射。',
  'sky-fire-crow':  '神火鴉 — 帶火藥的飛鳥。城防 ×0.5。',
  'cannon-man-slayer':'萬人敵 — 投擲火藥彈。爆炸 AOE 殺傷。',
  'red-cannon':     '紅夷大炮 — 西洋火炮。對城牆 +200% 殺傷。',
  'iron-cart-train':'鐵車連營 — 鐵車防御陣。對騎兵衝擊免疫。',
  'flame-thrower':  '猛火油櫃 — 宋代猛火油。噴射火油，AOE 烈火。',
  // ── Phase 67: 200 missing descriptions ──
  zhuolu:'涿鹿之戰 — 黃帝戰蚩尤，華夏文明肇始之戰。',
  dazexiang:'大澤鄉起義 — 陳勝吳廣首倡，「王侯將相寧有種乎」。',
  'chu-han':'楚漢相爭 — 項羽劉邦四年血戰，奠定漢朝四百年基業。',
  'mobei-battle':'漠北之戰 — 衛青霍去病大破匈奴主力，封狼居胥。',
  feishui:'淝水之戰 — 謝玄八千破苻堅百萬，東晉以少勝多。',
  'sui-chen':'隋滅陳 — 隋文帝統一南北，結束三百年分裂。',
  xuanwumen:'玄武門之變 — 李世民誅兄奪位，開啟貞觀之治。',
  anshi:'安史之亂 — 唐朝由盛轉衰，藩鎮割據之始。',
  huangchao:'黃巢之亂 — 唐末農民起義，攻破長安。',
  chanyuan:'澶淵之盟 — 宋遼百年和平，年納歲幣換和平。',
  jingkang:'靖康之恥 — 金兵破汴京，徽欽二帝被擄北上。',
  'fishing-castle':'釣魚城之戰 — 南宋孤城抗蒙古三十六年，蒙哥汗戰死。',
  'mongol-song':'蒙古滅宋 — 崖山海戰陸秀夫負幼帝跳海，宋亡。',
  'poyang-lake':'鄱陽湖之戰 — 朱元璋滅陳友諒，奠定明朝基業。',
  tumu:'土木堡之變 — 明英宗被瓦剌俘虜，五十萬大軍覆滅。',
  'beijing-defense':'北京保衛戰 — 于謙率軍守京師，擊退也先。',
  'wanli-three':'萬曆三大征 — 明朝三線作戰，國庫耗盡。',
  sarhu:'薩爾滸之戰 — 努爾哈赤集中破明朝四路大軍。',
  ningjin:'寧錦大捷 — 袁崇煥紅夷大炮守城，挫敗皇太極。',
  'yangzhou-ten':'揚州十日 — 清軍屠城十日，史可法殉國。',
  'jiading-three':'嘉定三屠 — 嘉定民眾抗清，三度被屠。',
  'three-feudatories':'平定三藩 — 康熙平吳三桂耿精忠尚之信，鞏固清初。',
  yaksa:'雅克薩之戰 — 清俄首次交兵，簽尼布楚條約。',
  'ulan-butong':'烏蘭布通之戰 — 康熙親征噶爾丹，火炮破駝陣。',
  'mengjin-cross':'孟津渡 — 武王伐紂前八百諸侯會盟。',
  'mawei-slope':'馬尾坡 — 安史之亂中楊貴妃被縊死之地。',
  'dingjun-mtn':'定軍山之戰 — 黃忠斬夏侯淵，劉備奪漢中。',
  'jieting-loss':'街亭失守 — 馬謖違諸葛軍令登山，致全軍潰敗。',
  'wuzhang-fall':'五丈原 — 諸葛亮第五次北伐病逝於此，星隕將星。',
  'jincheng-defend':'金城守 — 西涼門戶，多次守城經典。',
  'shangfang-valley':'上方谷 — 諸葛火困司馬，天降大雨救之。',
  'yiling-fire':'夷陵火 — 陸遜火燒連營七百里，劉備慘敗。',
  'hefei-defense':'合肥之戰 — 張遼八百破孫權十萬。',
  'jiameng-pass':'葭萌關 — 劉備入蜀第一站，馬超大戰張飛之地。',
  'xiapi-flood':'下邳水淹 — 曹操決沂泗之水淹下邳，呂布滅亡。',
  'jingzhou-fall':'荊州失 — 關羽輕敵被吳偷襲，荊州落入孫權。',
  'fancheng-flood':'樊城水淹 — 關羽決堤水淹七軍，威震華夏。',
  'changban-bridge':'長坂橋 — 張飛據水斷橋，喝退曹軍。',
  'guandu-grain':'官渡糧倉 — 曹操夜襲烏巢，斷袁紹糧道。',
  'red-cliffs-wind':'赤壁東風 — 諸葛借風助火攻，曹軍水陸覆沒。',
  'han-xin-count':'韓信點兵 — 多多益善，將兵之奇才。',
  'xiang-yu-horse':'項羽烏騅 — 西楚霸王烏騅馬，烏江自刎前贈亭長。',
  'fan-li-retire':'范蠡退隱 — 越王滅吳後棄官經商，三聚三散。',
  'lian-po-thorn':'廉頗負荊 — 將相和睦，國之大幸。',
  'zhao-she-vs-zhao':'趙奢戰韓 — 閼與之戰大破秦軍。',
  'wang-jian-six':'王翦掃六合 — 秦始皇用王翦六十萬兵滅楚。',
  'zhou-yafu':'周亞夫細柳 — 治軍嚴整，文帝親至轅門不得入。',
  'wei-qing-north':'衛青漠北 — 七次北擊匈奴，封大將軍。',
  'ban-chao-far':'班超遠征 — 投筆從戎，三十六騎定西域。',
  'ma-yuan-coffin':'馬援裹屍 — 老當益壯，馬革裹屍還。',
  'deng-yu-zhongxing':'鄧禹中興 — 雲台二十八將之首，光武中興功臣。',
  'kou-xun-henei':'寇恂河內 — 安內以送糧前線，後勤大師。',
  'feng-yi-cart':'馮異車戰 — 大樹將軍，戰功不爭。',
  'du-yu-bamboo':'杜預破竹 — 勢如破竹，一鼓作氣滅吳。',
  'xie-xuan-8k':'謝玄八千 — 北府兵以少勝多，淝水退苻堅。',
  'liu-yu-north':'劉裕北伐 — 收復長安洛陽，南朝最強武功。',
  'wei-rui-liang':'韋叡梁將 — 鍾離之戰大破北魏，南朝名將。',
  'yang-su-chen':'楊素破陳 — 隋朝水師統帥，順流而下滅陳。',
  'han-qinhu-cross':'韓擒虎渡江 — 五百精騎渡江擒陳後主。',
  'li-jing-turk':'李靖破突厥 — 三千騎夜襲頡利可汗，定漠北。',
  'guo-ziyi-lone':'郭子儀單騎 — 退回紇兵不血刃。',
  'yue-fei-yan':'岳飛槍法 — 撼山易撼岳家軍難。',
  'han-shizhong-water':'韓世忠水戰 — 黃天蕩困金兀朮四十八天。',
  'wu-jie-mtn':'吳玠和尚原 — 川陝守將，擋金兵入蜀。',
  'meng-gong-defend':'孟珙守城 — 南宋末期擎天柱，三次援襄陽。',
  'zhang-shijie-naval':'張世傑海戰 — 崖山海戰最後一搏。',
  'qi-jiguang-wokou':'戚繼光抗倭 — 鴛鴦陣破倭寇，東南海防。',
  'yu-dayou-fujian':'俞大猷福建 — 與戚繼光齊名，海陸雙絕。',
  'li-rusong-korea':'李如松援朝 — 平壤大捷，擊敗豐臣秀吉。',
  'song-yingchang-korea':'宋應昌朝鮮 — 援朝經略，戰後重整朝鮮。',
  'mao-wenlong-pidao':'毛文龍皮島 — 牽制後金，海上奇兵。',
  'lu-xiangsheng':'盧象升戰清 — 巨鹿之戰殉國，明末忠將。',
  'sun-chuanting-tang':'孫傳庭潼關 — 傳庭死而明亡，最後的長城。',
  'shi-kefa-yangzhou':'史可法揚州 — 孤城死守，殉國於此。',
  'zheng-zhilong-sea':'鄭芝龍海 — 海上王，鄭成功之父。',
  'liu-mingchuan-taiwan':'劉銘傳台灣 — 抗法首任台灣巡撫，建設台灣現代化。',
  'feng-zicai-zhennan':'馮子材鎮南關 — 六十九歲老將大破法軍。',
  'nie-shicheng-tianjin':'聶士成天津 — 庚子事變死守天津。',
  'duan-qirui-anhui':'段祺瑞皖派 — 北洋三傑之一，皖系軍閥首。',
  'feng-yuxiang-xian':'馮玉祥西安 — 倒戈將軍，西安事變策劃者之一。',
  'jin-school':'晉派兵法 — 司馬氏家學，重耐久守勢。',
  'han-school':'漢派兵法 — 高祖立國之策，輕兵速戰。',
  'wu-school':'吳派兵法 — 江東水戰專長，舟楫並用。',
  'shu-school':'蜀派兵法 — 諸葛之學，謀略為先。',
  'wei-school':'魏派兵法 — 曹操治軍，唯才是舉。',
  'yue-school':'越派兵法 — 勾踐臥薪嘗膽，伺機而動。',
  'qin-school':'秦派兵法 — 商鞅軍功爵制，重賞嚴罰。',
  'chu-school':'楚派兵法 — 項羽霸王之風，剛猛無敵。',
  'qi-school':'齊派兵法 — 孫子吳起田單，戰術之祖。',
  'yan-school':'燕派兵法 — 樂毅破齊，遠交近攻。',
  'mongol-school':'蒙古派 — 草原騎射，旋風機動。',
  'persian-school':'波斯派 — 中東騎兵與弓箭。',
  'japan-school':'日本派 — 武士道與忍術。',
  'korean-school':'朝鮮派 — 火炮與龜船結合。',
  'india-school':'天竺派 — 象兵與咒術。',
  'tibet-school':'吐蕃派 — 高原騎兵與密宗。',
  'manchu-school':'滿洲派 — 八旗鐵騎，騎射為本。',
  'tangut-school':'西夏派 — 党項弓兵與重騎。',
  'jurchen-school':'女真派 — 金朝開國，鐵浮屠拐子馬。',
  'khitan-school':'契丹派 — 遼朝雙軌制，騎兵稱雄。',
  'lubu-flying':'呂布飛將 — 人中呂布馬中赤兔，三國第一武將。',
  'guanyu-greendragon':'關羽青龍 — 青龍偃月刀，溫酒斬華雄。',
  'zhangfei-yelling':'張飛吼喝 — 當陽橋一聲吼，喝退曹軍。',
  'zhaoyun-shadow':'趙雲幻影 — 七進七出長坂坡，渾身是膽。',
  'machao-spear':'馬超銀槍 — 錦馬超，殺得曹操割鬚棄袍。',
  'huangzhong-bow':'黃忠寶弓 — 老將精射，定軍山斬夏侯。',
  'weiyan-charge':'魏延突進 — 子午谷奇謀，但被諸葛拒。',
  'jiangwei-disciple':'姜維傳人 — 諸葛遺志，九伐中原。',
  'caocao-poetry':'曹操詩才 — 「對酒當歌，人生幾何」，文武雙絕。',
  'xiahoudun-eye':'夏侯惇獨眼 — 拔矢啖睛，剛烈無比。',
  'dianwei-double-axe':'典韋雙戟 — 古之惡來，宛城殉主。',
  'xuchu-iron-fist':'許褚虎癡 — 曹操貼身侍衛，威震逍遙津。',
  'zhanghe-mobility':'張郃機動 — 巧變百出，魏五子之首。',
  'zhanglao-ambush':'張遼伏擊 — 逍遙津八百破十萬。',
  'panghong-sleep':'龐統假寐 — 鳳雛裝醉測劉備眼力。',
  'simayi-tortoise':'司馬龜縮 — 拒戰不出，等候孔明病逝。',
  'sunce-blade':'孫策小霸王 — 江東創業，二十出頭橫掃江南。',
  'sunquan-blue-eye':'孫權碧眼 — 紫髯藍睛，守業之主。',
  'zhouyu-music':'周郎曲誤 — 曲有誤，周郎顧。',
  'lumeng-study':'呂蒙刮目 — 士別三日，當刮目相看。',
  'luxun-fire':'陸遜火攻 — 火燒連營七百里，破劉備七十萬。',
  'taishici-arch':'太史慈射箭 — 神亭嶺單挑孫策，箭術絕倫。',
  'huanggai-old':'黃蓋老將 — 苦肉計詐降，赤壁建奇功。',
  'gan-ning-bell':'甘寧鈴聲 — 鈴聲叮噹過營，百騎劫曹營。',
  'zhuge-fan':'諸葛羽扇 — 羽扇綸巾，談笑間檣櫓灰飛煙滅。',
  'pang-tong-chain':'龐統連環 — 獻計鎖船，赤壁火攻基石。',
  'fazheng-strategy':'法正謀略 — 劉備平蜀首功，與諸葛並列。',
  'huangzhong-old-bow':'黃忠老當益壯 — 七十高齡仍能開強弓。',
  'jiang-ji-loyalty':'蔣濟忠誠 — 司馬懿掌權後憂憤而終。',
  'wenping-shield':'文聘盾陣 — 江夏太守，曹魏南線守將。',
  'yuejin-light':'樂進輕兵 — 善先登破敵，魏五子。',
  'lidian-scholar':'李典儒將 — 不喜爭功，魏將中清流。',
  'liu-bei-tears':'劉備淚水 — 哭得來的江山，仁主之姿。',
  'sun-jian-tiger':'孫堅猛虎 — 江東之虎，討董卓得玉璽。',
  'yuan-shao-noble':'袁紹貴族 — 四世三公，家世第一。',
  'yuan-shu-jade':'袁術玉璽 — 妄自稱帝，敗亡之兆。',
  'gongsun-zan-white':'公孫瓚白馬 — 白馬將軍，劉備早年盟友。',
  'dong-zhuo-tyrant':'董卓暴政 — 廢少帝立獻帝，火燒洛陽。',
  'wang-yun-plot':'王允連環 — 美人計除董卓。',
  'cao-zhi-poem':'曹植七步 — 七步成詩，「本是同根生」。',
  'tunnel-warfare':'地道戰 — 挖地道至城下，內外夾擊。',
  'pontoon-bridge':'浮橋 — 連舟為橋，渡大軍如平地。',
  'mining-walls':'挖牆 — 礦工挖牆基，城牆自塌。',
  'gate-tower':'城門樓 — 守城核心，箭手俯射。',
  'arrow-tower':'箭樓 — 城牆突出之箭塔，三面交叉火力。',
  'wall-corner':'敵樓 — 城角箭塔，無死角防御。',
  'moat-deep':'深溝 — 城外深溝，阻敵騎兵與雲梯。',
  caltrops:'蒺藜 — 鐵刺撒地，阻敵步騎。',
  'ballista-tower':'弩樓 — 安裝大型弩砲之箭樓。',
  'fire-arrow-tower':'火箭樓 — 守城火箭發射台。',
  'cauldron-oil':'熱油鍋 — 城頭熱油，敵爬梯時傾倒。',
  'rolling-logs':'滾木 — 大木從城頭滾下，砸破雲梯。',
  'spike-pit':'刺穴 — 偽裝陷阱，內藏尖刺。',
  'iron-stakes':'鐵蒺藜 — 鐵製刺釘，阻敵騎兵。',
  'observation-tower':'望樓 — 高處觀察敵情，預警攻擊。',
  'fake-letter':'偽書信 — 偽造敵將書信播亂敵內部。',
  'planted-spy':'潛伏間諜 — 派人臥底敵營，多年後啟動。',
  'reverse-spy':'反間之計 — 將敵奸細策反為己方眼線。',
  'turn-defector':'策反 — 暗中收買敵將領倒戈。',
  'morale-collapse':'士氣崩潰 — 製造輿論瓦解敵軍鬥志。',
  'banner-burn':'焚旗 — 焚燒敵軍旗，動搖軍心。',
  'name-call':'指名點殺 — 陣前點將激怒，引敵單挑。',
  'mass-execution':'處決恐嚇 — 公開處決俘虜，震懾敵軍。',
  'mercy-show':'示恩懷柔 — 釋放俘虜換取信任。',
  'hostage-display':'懸首示眾 — 高懸敵將首級於城頭。',
  'public-feast':'設宴款軍 — 公開慶功宴提振士氣。',
  'rumor-defection':'謠言叛亂 — 散布某將領將叛之言。',
  'shame-disgrace':'羞辱降將 — 公開羞辱以警示同僚。',
  'ancestor-mock':'辱其先祖 — 罵敵將祖宗以激其魯莽。',
  'family-threat':'家眷威脅 — 暗示加害敵將家屬迫其降。',
  'salt-monopoly':'鹽鐵專營 — 朝廷專營鹽鐵，財政命脈。',
  'iron-monopoly':'鐵專營 — 控制兵器原料源頭。',
  'tea-trade':'茶馬貿易 — 用茶葉換取邊塞馬匹。',
  'silk-road':'絲綢之路 — 連接東西的商貿要道。',
  'mint-coin':'鑄幣 — 統一貨幣，控制經濟。',
  'tax-cut':'輕徭薄賦 — 減稅以安民心。',
  'land-reform':'均田 — 按人均分土地，恢復生產。',
  'merchant-tax':'商稅 — 對商人徵稅，補充國庫。',
  'tribute-system':'朝貢 — 接受邊境各國貢品，宣示宗主。',
  'forge-currency':'偽造錢幣 — 偽幣擾亂敵國經濟。',
  'spy-network':'間諜網 — 建立覆蓋敵境的情報網絡。',
  'double-agent':'雙面間諜 — 同時為兩方情報工作。',
  'sleeper-cell':'潛伏細胞 — 多年潛伏，戰時激活。',
  'dead-drop':'死信箱 — 隱秘交接情報之點。',
  'fake-defector':'假降 — 假裝投降實則為內應。',
  'court-bribery':'宮廷賄賂 — 收買敵國重臣。',
  'maid-spy':'侍女間諜 — 後宮安插女眼線。',
  'letter-intercept':'截獲書信 — 截獲敵國機密通訊。',
  'signal-flag':'信號旗 — 旗號傳令，戰場無延遲。',
  'carrier-pigeon':'信鴿 — 鴿哨遠程傳令。',
  'sun-ce-mirror':'孫策鏡破 — 鏡破之兆，江東小霸王中道夭折。',
  'cao-rui-vase':'曹叡奢華 — 大興土木造奢宮，國力消耗。',
  'liu-shan-stupid':'劉禪庸主 — 「此間樂，不思蜀」，亡國之君。',
  'da-qiao-marriage':'大喬聯姻 — 江東二喬聯姻孫策周瑜，鞏固勢力。',
  'dong-zhuo-fat':'董卓肥油 — 死後肚臍點燈，肥油燃三日。',
  'lu-zhi-master':'盧植師教 — 劉備公孫瓚之師，名教大儒。',
  'cai-yong-lute':'蔡邕焦尾 — 焦尾琴，琴中極品。',
  'mi-heng-drum':'禰衡擊鼓 — 裸衣罵曹，狂士本色。',
  'zhang-jiao-yellow':'張角黃天 — 「蒼天已死，黃天當立」，黃巾起義。',
  'zhang-lu-rice':'張魯五斗 — 五斗米道首領，據漢中三十年。',
};

const CATEGORIES: CatalogCategory[] = [
  { key: 'melee',    zh: '近戰', en: 'Melee',    color: '#b8442e' },
  { key: 'ranged',   zh: '遠程', en: 'Ranged',   color: '#b8c87a' },
  { key: 'mystic',   zh: '奇門', en: 'Mystic',   color: '#c178c7' },
  { key: 'disrupt',  zh: '擾亂', en: 'Disrupt',  color: '#88b7e8' },
  { key: 'strategy', zh: '策略', en: 'Strategy', color: '#d4a84a' },
];

interface Props { onClose: () => void; }

export function TacticsModal({ onClose }: Props) {
  const items: CatalogItem[] = Object.entries(TACTIC_DEFS).map(([id, def]) => ({
    id,
    zh: def.zh,
    en: def.en,
    description: TACTIC_DESC[id] ?? '',
    category: TACTIC_CATEGORY[id] ?? 'melee',
    badge: bonusBadge(id),
  }));
  return (
    <CatalogModal
      onClose={onClose}
      title={{ zh: '戰法', en: 'Tactics' }}
      items={items}
      categories={CATEGORIES}
    />
  );
}
